In [1272]:
import pandas as pd

In [1273]:
import re
import unicodedata



def normalizar_instituicao(nome):

    mapeamento = [
        (r"(FLUMIN|UFF|INFES/UFF|IC/UFF|PPGCI/UFF)",
         "Universidade Federal Fluminense"),

        (r"(SAO PAULO|USP|ICMC|POLITECNICA|EACH|UNIVERSITY OF SÃO PAULO)",
         "Universidade de São Paulo"),

        (r"(MINAS GERAIS|UFMG|BIOINFORMATICA|DCC/UFMG)",
         "Universidade Federal de Minas Gerais"),

        (r"(RIO DE JANEIRO|UFRJ|COPPE|PPGI/UFRJ|BNDES|IBCCF|PPGEN|CISI/COPPE)",
         "Universidade Federal do Rio de Janeiro"),

        (r"(CAMPINA GRANDE|UFCG|CAMINA GRANDE)",
         "Universidade Federal de Campina Grande"),

        (r"(CAMPINAS|UNICAMP|CEPAGRI)",
         "Universidade Estadual de Campinas"),

        (r"(CEARA|UFC)",
         "Universidade Federal do Ceará"),

        (r"(PERNAMBUCO|UFPE|CIN/UFPE|UFRPE|AGRESTE)",
         "Universidade Federal de Pernambuco"),

        (r"(SAO CARLOS|UFSCAR)",
         "Universidade Federal de São Carlos"),

        (r"(PUC RIO|PONTIFICAL CATHOLIC UNIVERSITY OF RIO DE JANEIRO)",
         "Pontifícia Universidade Católica do Rio de Janeiro"),

        (r"(GOIAS|UFG)",
         "Universidade Federal de Goiás"),

        (r"(PARANA|UFPR)",
         "Universidade Federal do Paraná"),

        (r"(UBERLANDIA|UFU)",
         "Universidade Federal de Uberlândia"),

        (r"(OURO PRETO|UFOP)",
         "Universidade Federal de Ouro Preto"),

        (r"(SANTA CATARINA|UFSC)",
         "Universidade Federal de Santa Catarina"),

        (r"(RIO GRANDE DO SUL|UFRGS)",
         "Universidade Federal do Rio Grande do Sul"),

        (r"(AMAZONAS|UFAM)",
         "Universidade Federal do Amazonas"),

        (r"(BRASILIA|UNB)",
         "Universidade de Brasília"),

        (r"(SAO JOAO DEL REI|UFSJ)",
         "Universidade Federal de São João Del Rei"),

        (r"(FORTALEZA|UNIFOR)",
         "Universidade de Fortaleza"),

        (r"(INSTITUTO FEDERAL|IFSP|IFMG|IFPR|IFNMG|IFPB|IFRS|IFSUL|IF SUDOESTE)",
         "Institutos Federais"),

        (r"(CEFET)",
         "Centro Federal de Educação Tecnológica"),

        (r"(UTFPR|TECHNOLOGY PARANA)",
         "Universidade Tecnológica Federal do Paraná"),

        (r"(AERONAUTICA|ITA)",
         "Instituto Tecnológico de Aeronáutica"),

        (r"(FIOCRUZ|OSWALDO CRUZ)",
         "Fundação Oswaldo Cruz"),

        (r"(EMBRAPA)",
         "Empresa Brasileira de Pesquisa Agropecuária"),

        (r"(IBM)",
         "IBM Research"),

        (r"(JUSBRASIL)",
         "Jusbrasil"),

        (r"(NO AFFILIATION DECLARED	|NOT INFORMED)",
         "Sem Afiliação"),

        (r"(BRAZIL)",
         "BRASIL")
    ]

    if pd.isna(nome):
        return None

    for padrao, nome_padrao in mapeamento:
        if re.search(padrao, nome):
            return nome_padrao.upper()

    return nome

In [ ]:
df = pd.read_json(
    'C:/repository/TCC/data/raw/dados_artigos.json')

In [1275]:
pd.set_option('display.max_rows', None)
pd.set_option('display.max_columns', None)
pd.set_option('display.width', None)
pd.set_option('display.max_colwidth', None)

Explode nos autores

In [1276]:
df_autores = df.explode('autores')

autores = pd.json_normalize(df_autores['autores'])

instituicoes = autores['inst']

Autores

In [1277]:
df['autores'] = autores.groupby(level=0).agg({'nome': lambda x: ', '.join(x)})

# Separar os autores em colunas distintas
df['autor_1'] = df['autores'].str.split(',').str[0].str.strip().str.upper().fillna(None)
df['autor_2'] = df['autores'].str.split(',').str[1].str.strip().str.upper().fillna(None)
df['autor_3'] = df['autores'].str.split(',').str[2].str.strip().str.upper().fillna(None)
df['autor_4'] = df['autores'].str.split(',').str[3].str.strip().str.upper().fillna(None)
df['autor_5'] = df['autores'].str.split(',').str[4].str.strip().str.upper().fillna(None)
df['autor_6'] = df['autores'].str.split(',').str[5].str.strip().str.upper().fillna(None)
df['autor_7'] = df['autores'].str.split(',').str[6].str.strip().str.upper().fillna(None)
df['autor_8'] = df['autores'].str.split(',').str[7].str.strip().str.upper().fillna(None)

Instituições

In [1278]:
df['instituicoes'] = autores.groupby(level=0).agg({'inst': lambda x: ', '.join(x)})

In [1279]:
df.head(2)

,titulo,data,doi,volume,autores,keywords,url,autor_1,autor_2,autor_3,autor_4,autor_5,autor_6,autor_7,autor_8,instituicoes
0,Analysis of Expenses from Brazilian Federal Deputies between 2015 and 2018,Data Desconhecida,10.5753/jidm.2025.3383,Vol. 16 No. 1 (2025),"Felippe Pires Ferreira, Ilan S. G. de Figueiredo, Larissa R. Teixeira, William Zaniboni Silva, Caetano Traina Junior, Cristina Dutra de Aguiar, Robson L. F. Cordeiro","[Analysis of expenses, Public expenses, Brazilian deputies, Outliers]",https://journals-sol.sbc.org.br/index.php/jidm/article/view/3383,FELIPPE PIRES FERREIRA,ILAN S. G. DE FIGUEIREDO,LARISSA R. TEIXEIRA,WILLIAM ZANIBONI SILVA,CAETANO TRAINA JUNIOR,CRISTINA DUTRA DE AGUIAR,ROBSON L. F. CORDEIRO,None,"Universidade de São Paulo, Universidade de São Paulo, Universidade de São Paulo, Universidade de São Paulo, Universidade de São Paulo, Universidade de São Paulo, Carnegie Mellon University"
1,Exploratory Analysis of Microdata from the National High School Exam - Enem: Performance and Specificities of the Participants,Data Desconhecida,10.5753/jidm.2025.3657,Vol. 16 No. 1 (2025),"João Augusto Fernandes Barbosa, Robson Leonardo Ferreira Cordeiro","[Enem, Disability, Exploratory data analysis, Education, Performance]",https://journals-sol.sbc.org.br/index.php/jidm/article/view/3657,JOÃO AUGUSTO FERNANDES BARBOSA,ROBSON LEONARDO FERREIRA CORDEIRO,None,None,None,None,None,None,"University of São Paulo, Carnegie Mellon University"

In [1280]:
df['instituicoes'] = autores.groupby(level=0).agg({'inst': lambda x: ', '.join(x)})

# Separar as instituições em colunas distintas
df['instituicao_1'] = df['instituicoes'].str.split(',').str[0].str.strip().str.upper().fillna(None)
df['instituicao_2'] = df['instituicoes'].str.split(',').str[1].str.strip().str.upper().fillna(None)
df['instituicao_3'] = df['instituicoes'].str.split(',').str[2].str.strip().str.upper().fillna(None)
df['instituicao_4'] = df['instituicoes'].str.split(',').str[3].str.strip().str.upper().fillna(None)
df['instituicao_5'] = df['instituicoes'].str.split(',').str[4].str.strip().str.upper().fillna(None)
df['instituicao_6'] = df['instituicoes'].str.split(',').str[5].str.strip().str.upper().fillna(None)
df['instituicao_7'] = df['instituicoes'].str.split(',').str[6].str.strip().str.upper().fillna(None)
df['instituicao_8'] = df['instituicoes'].str.split(',').str[7].str.strip().str.upper().fillna(None)

Criar ID

In [1281]:
df['id'] = df['url'].str.split('/').str[-1].str.replace('.html', '', regex=False)

In [1282]:
# Reordenar as colunas para colocar o ID no início
colunas = ['id'] + [col for col in df.columns if col != 'id']
df = df[colunas]

In [1283]:
df = df.drop(columns=['autores', 'url', 'doi', 'instituicoes']).reset_index(drop=True)

In [1284]:
df.head(2)

,id,titulo,data,volume,keywords,autor_1,autor_2,autor_3,autor_4,autor_5,autor_6,autor_7,autor_8,instituicao_1,instituicao_2,instituicao_3,instituicao_4,instituicao_5,instituicao_6,instituicao_7,instituicao_8
0,3383,Analysis of Expenses from Brazilian Federal Deputies between 2015 and 2018,Data Desconhecida,Vol. 16 No. 1 (2025),"[Analysis of expenses, Public expenses, Brazilian deputies, Outliers]",FELIPPE PIRES FERREIRA,ILAN S. G. DE FIGUEIREDO,LARISSA R. TEIXEIRA,WILLIAM ZANIBONI SILVA,CAETANO TRAINA JUNIOR,CRISTINA DUTRA DE AGUIAR,ROBSON L. F. CORDEIRO,None,UNIVERSIDADE DE SÃO PAULO,UNIVERSIDADE DE SÃO PAULO,UNIVERSIDADE DE SÃO PAULO,UNIVERSIDADE DE SÃO PAULO,UNIVERSIDADE DE SÃO PAULO,UNIVERSIDADE DE SÃO PAULO,CARNEGIE MELLON UNIVERSITY,None
1,3657,Exploratory Analysis of Microdata from the National High School Exam - Enem: Performance and Specificities of the Participants,Data Desconhecida,Vol. 16 No. 1 (2025),"[Enem, Disability, Exploratory data analysis, Education, Performance]",JOÃO AUGUSTO FERNANDES BARBOSA,ROBSON LEONARDO FERREIRA CORDEIRO,None,None,None,None,None,None,UNIVERSITY OF SÃO PAULO,CARNEGIE MELLON UNIVERSITY,None,None,None,None,None,None

Keywords

In [1285]:
keywords = df.explode('keywords')

df["keywords"] = (
    keywords.groupby(level=0)
            .agg({'keywords': lambda x: ', '.join(x.dropna().astype(str))})
)


# Separar as palavras-chave em colunas distintas
df['keyword_1'] = df['keywords'].str.split(',').str[0].str.strip().str.upper().fillna(None)
df['keyword_2'] = df['keywords'].str.split(',').str[1].str.strip().str.upper().fillna(None)
df['keyword_3'] = df['keywords'].str.split(',').str[2].str.strip().str.upper().fillna(None)
df['keyword_4'] = df['keywords'].str.split(',').str[3].str.strip().str.upper().fillna(None)
df['keyword_5'] = df['keywords'].str.split(',').str[4].str.strip().str.upper().fillna(None)

Padronizar nomes

In [1286]:
dcols = [f'instituicao_{i}' for i in range(1, 9)]

df[cols] = df[cols].apply(lambda col: col.apply(normalizar_instituicao))

### VALIDAR

In [1299]:
cols = [f'instituicao_{i}' for i in range(1, 9)]

df_filtrado = df[
    df[cols].apply(
        lambda col: col.str.contains('FLUMINENSE', case=False, na=False)
    ).any(axis=1)
]

df_filtrado

,id,titulo,data,volume,keywords,autor_1,autor_2,autor_3,autor_4,autor_5,autor_6,autor_7,autor_8,instituicao_1,instituicao_2,instituicao_3,instituicao_4,instituicao_5,instituicao_6,instituicao_7,instituicao_8,keyword_1,keyword_2,keyword_3,keyword_4,keyword_5
13,4110,Towards Data Summarization of Multi-Aspect Trajectories Based on Spatio-Temporal Segmentation,Data Desconhecida,Vol. 16 No. 1 (2025),"Multiple aspect trajectory, Representative trajectory, Trajectory summarization",VANESSA LAGO MACHADO,TARLIS TORTELLI PORTELA,GEOMAR ANDRÉ SCHREINER,RONALDO DOS SANTOS MELLO,None,None,None,None,UNIVERSIDADE FEDERAL DE SANTA CATARINA,INSTITUTOS FEDERAIS,INSTITUTOS FEDERAIS,UNIVERSIDADE FEDERAL FLUMINENSE,UNIVERSIDADE FEDERAL DE SANTA CATARINA,NaN,NaN,NaN,MULTIPLE ASPECT TRAJECTORY,REPRESENTATIVE TRAJECTORY,TRAJECTORY SUMMARIZATION,None,None
18,4361,Exploring Evolutionary Patterns: A Jupyter Notebook for Discovering Frequent Subtrees in Phylogenetic Tree Databases,Data Desconhecida,Vol. 16 No. 1 (2025),"Phylogenetics, Frequent subtrees, Bioinformatics, Workflows",JOÃO VITOR MORAES,CAMILA FERRARI,ISABEL ROSSETI,DANIEL DE OLIVEIRA,None,None,None,None,UNIVERSIDADE FEDERAL FLUMINENSE,UNIVERSIDADE FEDERAL FLUMINENSE,UNIVERSIDADE FEDERAL FLUMINENSE,UNIVERSIDADE FEDERAL FLUMINENSE,NaN,NaN,NaN,NaN,PHYLOGENETICS,FREQUENT SUBTREES,BIOINFORMATICS,WORKFLOWS,None
47,3564,Datasets for Portuguese Legal Semantic Textual Similarity,Data Desconhecida,Vol. 15 No. 1 (2024),"Legal dataset, Semantic textual similarity, Data annotation",DANIEL DA SILVA JUNIOR,PAULO ROBERTO DOS SANTOS CORVAL,DANIEL DE OLIVEIRA,ALINE PAES,None,None,None,None,UNIVERSIDADE FEDERAL FLUMINENSE,UNIVERSIDADE FEDERAL FLUMINENSE,UNIVERSIDADE FEDERAL FLUMINENSE,UNIVERSIDADE FEDERAL FLUMINENSE,NaN,NaN,NaN,NaN,LEGAL DATASET,SEMANTIC TEXTUAL SIMILARITY,DATA ANNOTATION,None,None
59,3189,Hurricane: a Dataflow-oriented Data Service for Smart Cities Applications,Data Desconhecida,Vol. 14 No. 1 (2023),"Smart cities, Data management, Data integration",MAICON BANNI,MARIA LUIZA FALCI,ISABEL ROSSETI,DANIEL DE OLIVEIRA,None,None,None,None,UNIVERSIDADE FEDERAL FLUMINENSE,UNIVERSIDADE FEDERAL FLUMINENSE,UNIVERSIDADE FEDERAL FLUMINENSE,UNIVERSIDADE FEDERAL FLUMINENSE,NaN,NaN,NaN,NaN,SMART CITIES,DATA MANAGEMENT,DATA INTEGRATION,None,None
62,3233,ORBITER: a Lightweight Framework for Automatic Deployment of Big Data Applications on Serverless Architectures,Data Desconhecida,Vol. 14 No. 2 (2023),"Serverless, Faas, Big data applications",JOÃO LOUREIRO,JOSÉ MARIA MONTEIRO,MARCOS BEDO,DANIEL DE OLIVEIRA,None,None,None,None,UNIVERSIDADE FEDERAL FLUMINENSE,UNIVERSIDADE FEDERAL DO CEARÁ,UNIVERSIDADE FEDERAL FLUMINENSE,UNIVERSIDADE FEDERAL FLUMINENSE,NaN,NaN,NaN,NaN,SERVERLESS,FAAS,BIG DATA APPLICATIONS,None,None
66,2564,Sentiment Analysis in Tweets: Exploring Instance-based Transfer Learning for Dataset Enrichment,Data Desconhecida,Vol. 13 No. 6 (2022),"Machine learning, Sentiment analysis, Supervised learning, Transfer learning, Twitter",ELISEU GUIMARÃES,DANIELA VIANNA,ALINE PAES,ALEXANDRE PLASTINO,None,None,None,None,UNIVERSIDADE FEDERAL FLUMINENSE,UNIVERSIDADE FEDERAL DO AMAZONAS,UNIVERSIDADE FEDERAL FLUMINENSE,UNIVERSIDADE FEDERAL FLUMINENSE,NaN,NaN,NaN,NaN,MACHINE LEARNING,SENTIMENT ANALYSIS,SUPERVISED LEARNING,TRANSFER LEARNING,TWITTER
71,2544,Capturing Provenance from Deep Learning Applications Using Keras-Prov and Colab: a Practical Approach,Data Desconhecida,Vol. 13 No. 5 (2022),"Deep learning, Metadata, Provenance",DÉBORA PINA,LILIANE KUNSTMANN,FELIPE BEVILAQUA,ISABELA SIQUEIRA,ALAN LYRA,DANIEL DE OLIVEIRA,MARTA MATTOSO,None,UNIVERSIDADE FEDERAL DO RIO DE JANEIRO,UNIVERSIDADE FEDERAL DO RIO DE JANEIRO,UNIVERSIDADE FEDERAL DO RIO DE JANEIRO,UNIVERSIDADE FEDERAL DO RIO DE JANEIRO,UNIVERSIDADE FEDERAL DO RIO DE JANEIRO,UNIVERSIDADE FEDERAL FLUMINENSE,UNIVERSIDADE FEDERAL DO RIO DE JANEIRO,NaN,DEEP LEARNING,METADATA,PROVENANCE,None,None
74,2059,P+RProv: Prospective+Retrospective Provenance Graphs of Python Scripts,Data Desconhecida,Vol. 13 No. 4 (2022),"Diagrams, Prospective provenance, Provenance visualization, Scripts",VITOR GAMA LEMOS,JOÃO FELIPE PIMENTEL,BRUNO ERBISTI,VANESSA BRAGANHOLO,None,None,None,None,UNIVERSIDADE FEDERAL FLUMINENSE,UNIVERSIDADE FEDERAL FLUMINENSE,UNIVERSIDADE FEDERAL FLUMINENSE,UNIVERSIDADE FEDERAL FLUMINENSE,NaN,NaN,NaN,NaN,DIAGRAMS,PROSPECTIVE PROVENANCE,PROVENANCE VISUALIZATION,SCRIPTS,None
80,2513,Beyond Click-and-View: a Comparative Study of Data Management Approaches for Interactive Visualization,Data Desconhecida,Vol. 13 No. 3 (2022),"Interactive vis, Database evaluation",LORENNA CHRIST'NA NASCIMENTO,RODOLFO P. CHAGAS,MARCOS LAGE,DANIEL DE OLIVEIRA,None,None,None,None,UNIVERSIDADE FEDERAL FLUMINENSE,UNIVERSIDADE FEDERAL FLUMINENSE,UNIVERSIDADE FEDERAL FLUMINENSE,UNIVERSIDADE FEDERAL FLUMINENSE,NaN,NaN,NaN,NaN,INTERACTIVE VIS,DATABASE EVALUATION,None,None,None
90,2435,A Framework to Compute Entity Relatedness in Large RDF Knowledge Bases,Data Desconhecida,Vol. 13 No. 2 (2022),"Entity relatedness, Rdf graph, Path search strategy, Entity similarity, Path ranking, Dbpedia, Spark",JAVIER GUILLOT JIMÉNEZ,LUIZ ANDRÉ P. PAES LEME,YENIER TORRES IZQUIERDO,ANGELO BATISTA NEVES,MARCO A. CASANOVA,None,None,None,PUC-RIO,UNIVERSIDADE FEDERAL FLUMINENSE,PUC-RIO,PUC-RIO,PUC-RIO,NaN,NaN,NaN,ENTITY RELATEDNESS,RDF GRAPH,PATH SEARCH STRATEGY,ENTITY SIMILARITY,PATH RANKING
102,2355,PolRoute-DS: a Crime Dataset for Optimization-based Police Patrol Routing,Data Desconhecida,Vol. 13 No. 1 (2022),"Crime dataset, Predictive policing, Police routing",BRUNO CUNHA SÁ,GUSTAVO MULLER,MAICON BANNI,WAGNER SANTOS,MARCOS LAGE,ISABEL ROSSETI,YURI FROTA,DANIEL DE OLIVEIRA,UNIVERSIDADE FEDERAL FLUMINENSE,UNIVERSIDADE FEDERAL FLUMINENSE,UNIVERSIDADE FEDERAL FLUMINENSE,UNIVERSIDADE FEDERAL FLUMINENSE,UNIVERSIDADE FEDERAL FLUMINENSE,UNIVERSIDADE FEDERAL FLUMINENSE,UNIVERSIDADE FEDERAL FLUMINENSE,UNIVERSIDADE FEDERAL FLUMINENSE,CRIME DATASET,PREDICTIVE POLICING,POLICE ROUTING,None,None
106,1924,Online Deep Learning Hyperparameter Tuning based on Provenance Analysis,Data Desconhecida,Vol. 12 No. 5 (2021),"Deep learning, Provenance, Hyperparameter tuning",LILIANE KUNSTMANN,DÉBORA PINA,FILIPE SILVA,ALINE PAES,PATRICK VALDURIEZ,DANIEL DE OLIVEIRA,MARTA MATTOSO,None,UNIVERSIDADE FEDERAL DO RIO DE JANEIRO,UNIVERSIDADE FEDERAL DO RIO DE JANEIRO,UNIVERSIDADE FEDERAL DO RIO DE JANEIRO,UNIVERSIDADE FEDERAL FLUMINENSE,INRIA - UNIVERSITY OF MONTPELLIER,UNIVERSIDADE FEDERAL FLUMINENSE,UNIVERSIDADE FEDERAL DO RIO DE JANEIRO,NaN,DEEP LEARNING,PROVENANCE,HYPERPARAMETER TUNING,None,None
107,1923,Multimodal Provenance-based Analysis of Collaboration in Business Processes,Data Desconhecida,Vol. 12 No. 5 (2021),"Multimodal data provenance, Provenance data, Business process data",MARIA LUIZA FALCI,ANDRÉA MAGALHÃES,ALINE PAES,VANESSA BRAGANHOLO,DANIEL DE OLIVEIRA,None,None,None,UNIVERSIDADE FEDERAL FLUMINENSE,UNIVERSIDADE FEDERAL FLUMINENSE,UNIVERSIDADE FEDERAL FLUMINENSE,UNIVERSIDADE FEDERAL FLUMINENSE,UNIVERSIDADE FEDERAL FLUMINENSE,NaN,NaN,NaN,MULTIMODAL DATA PROVENANCE,PROVENANCE DATA,BUSINESS PROCESS DATA,None,None
114,1904,A Platform for Keyword Search and its Application for COVID-19 Pandemic Data,Data Desconhecida,Vol. 12 No. 5 (2021),"Covid-19 data, Platform, Keyword search, Sql",YENIER T. IZQUIERDO,GRETTEL M. GARCIA,MELISSA LEMOS,ALEXANDRE NOVELLO,BRUNO NOVELLI,CLEBER DAMASCENO,LUIZ ANDRÉ P. P. LEME,MARCO A. CASANOVA,PUC-RIO,PUC-RIO,PUC-RIO,PUC-RIO,PUC-RIO,PUC-RIO,UNIVERSIDADE FEDERAL FLUMINENSE,PUC-RIO,COVID-19 DATA,PLATFORM,KEYWORD SEARCH,SQL,None
121,1968,Evaluating Temporal Bias in Time Series Event Detection Methods,Data Desconhecida,Vol. 12 No. 3 (2021),"Event detection, Time series, Benchmarking, Temporal bias",LUCIANA ESCOBAR,REBECCA SALLES,JANIO LIMA,CRISTIANE GEA,LAIS BARONI,ARTUR ZIVIANI,PAULO PIRES,FLAVIA DELICATO,UNIVERSIDADE FEDERAL DO RIO DE JANEIRO,UNIVERSIDADE FEDERAL DO RIO DE JANEIRO,UNIVERSIDADE FEDERAL DO RIO DE JANEIRO,UNIVERSIDADE FEDERAL DO RIO DE JANEIRO,UNIVERSIDADE FEDERAL DO RIO DE JANEIRO,LABORATÓRIO NACIONAL DE COMPUTAÇÃO CIENTÍFICA,UNIVERSIDADE FEDERAL FLUMINENSE,UNIVERSIDADE FEDERAL FLUMINENSE,EVENT DETECTION,TIME SERIES,BENCHMARKING,TEMPORAL BIAS,None
124,1917,An empirical assessment of quality metrics for diversified similarity searching,Data Desconhecida,Vol. 12 No. 3 (2021),"Metric spaces, Diversified similarity searching, Result diversification, Similarity searching",CAMILA R. LOPES,LÚCIO F. D. SANTOS,DANIEL L. JASBICK,DANIEL DE OLIVEIRA,MARCOS BEDO,None,None,None,UNIVERSIDADE FEDERAL DE MINAS GERAIS,UNIVERSIDADE FEDERAL DE MINAS GERAIS,UNIVERSIDADE FEDERAL FLUMINENSE,UNIVERSIDADE FEDERAL FLUMINENSE,UNIVERSIDADE FEDERAL FLUMINENSE,UNIVERSIDADE FEDERAL FLUMINENSE,NaN,NaN,METRIC SPACES,DIVERSIFIED SIMILARITY SEARCHING,RESULT DIVERSIFICATION,SIMILARITY SEARCHING,None
127,1990,J-EDA: A workbench for tuning similarity and diversity search parameters in content-based image retrieval,Data Desconhecida,Vol. 12 No. 2 (2021),"Content-based image retrieval, Result diversification, Similarity searching",JOÃO V. O. NOVAES,LÚCIO F. D. SANTOS,LUIZ OLMES CARVALHO,DANIEL DE OLIVEIRA,MARCOS V. N. BEDO,AGMA J. M. TRAINA,CAETANO TRAINA JR.,None,UNIVERSIDADE DE SÃO PAULO,UNIVERSIDADE FEDERAL DE MINAS GERAIS,INSTITUTO TECNOLÓGICO DE AERONÁUTICA,UNIVERSIDADE FEDERAL FLUMINENSE,UNIVERSIDADE FEDERAL FLUMINENSE,UNIVERSIDADE DE SÃO PAULO,UNIVERSIDADE DE SÃO PAULO,NaN,CONTENT-BASED IMAGE RETRIEVAL,RESULT DIVERSIFICATION,SIMILARITY SEARCHING,None,None
128,1988,Managing Hypothesis of Scientific Experiments with PhenoManager,Data Desconhecida,Vol. 12 No. 2 (2021),"Scientific experiment, Phenomena, Hypothesis, Scientific workflows, Project management",LEONARDO RAMOS,FABIO PORTO,DANIEL DE OLIVEIRA,None,None,None,None,None,UNIVERSIDADE FEDERAL FLUMINENSE,NATIONAL LABORATORY OF SCIENTIFIC COMPUTING (LNCC),UNIVERSIDADE FEDERAL FLUMINENSE,NaN,NaN,NaN,NaN,NaN,SCIENTIFIC EXPERIMENT,PHENOMENA,HYPOTHESIS,SCIENTIFIC WORKFLOWS,PROJECT MANAGEMENT
140,2017,Polyflow: a Polystore-compliant Mechanism to Provide Interoperability to Heterogeneous Provenance Graphs,Data Desconhecida,Vol. 11 No. 3 (2020),"Polystore, Syntactic interoperability, Semantic interoperability",YAN MENDES,DANIEL DE OLIVEIRA,VICTOR STRÖELE,None,None,None,None,None,FEDERAL UNIVERSITY OF JUIZ DE FORA,UNIVERSIDADE FEDERAL FLUMINENSE,FEDERAL UNIVERSITY OF JUIZ DE FORA,NaN,NaN,NaN,NaN,NaN,POLYSTORE,SYNTACTIC INTEROPERABILITY,SEMANTIC INTEROPERABILITY,None,None
182,1635,Beyond hit-or-miss: a comparative study of synopses for similarity searching,Data Desconhecida,Vol. 9 No. 1 (2018),"Similarity searching, Cost model, Synopsis, Distance distribution",MARCOS V. N. BEDO,DANIEL DE OLIVEIRA,AGMA J. M. TRAINA,CAETANO TRAINA JR.,None,None,None,None,UNIVERSIDADE FEDERAL FLUMINENSE,UNIVERSIDADE FEDERAL FLUMINENSE,UNIVERSIDADE DE SÃO PAULO,UNIVERSIDADE DE SÃO PAULO,NaN,NaN,NaN,NaN,SIMILARITY SEARCHING,COST MODEL,SYNOPSIS,DISTANCE DISTRIBUTION,None
185,1638,Towards an Empirical Evaluation of Scientific Data Indexing and Querying,Data Desconhecida,Vol. 9 No. 1 (2018),"Computational fluid dynamics, Dataflow management, Scientific data indexing, Scientific data querying",THAYLON GUEDES,VÍTOR SILVA,JOSÉ CAMATA,MARCOS V. N. BEDO,MARTA MATTOSO,DANIEL DE OLIVEIRA,None,None,UNIVERSIDADE FEDERAL FLUMINENSE,UNIVERSIDADE FEDERAL DO RIO DE JANEIRO,UNIVERSIDADE FEDERAL DE JUIZ DE FORA,UNIVERSIDADE FEDERAL FLUMINENSE,UNIVERSIDADE FEDERAL DO RIO DE JANEIRO,UNIVERSIDADE FEDERAL FLUMINENSE,NaN,NaN,COMPUTATIONAL FLUID DYNAMICS,DATAFLOW MANAGEMENT,SCIENTIFIC DATA INDEXING,SCIENTIFIC DATA QUERYING,None
198,1615,Spatiotemporal Anomaly Detection Applied to Flow Measurement Points in Natural Gas Production Plants,Data Desconhecida,Vol. 8 No. 2 (2017),"Anomaly detection, Dynamic bayes net, Flow measurement points",HADRIEL TOLEDO LIMA,FLAVIA BERNARDINI,None,None,None,None,None,None,UNIVERSIDADE FEDERAL FLUMINENSE,UNIVERSIDADE FEDERAL FLUMINENSE,NaN,NaN,NaN,NaN,NaN,NaN,ANOMALY DETECTION,DYNAMIC BAYES NET,FLOW MEASUREMENT POINTS,None,None
199,1603,Querying Provenance along with External Domain Data Using Prolog,Data Desconhecida,Vol. 8 No. 1 (2017),"Provenance analysis, Scientific experiments, Workflows",WELLINGTON OLIVEIRA,KARY A. C. S. OCAÑA,DANIEL DE OLIVEIRA,VANESSA BRAGANHOLO,None,None,None,None,UNIVERSIDADE FEDERAL FLUMINENSE,LABORATÓRIO NACIONAL DE COMPUTAÇÃO CIENTÍFICA,UNIVERSIDADE FEDERAL FLUMINENSE,UNIVERSIDADE FEDERAL FLUMINENSE,NaN,NaN,NaN,NaN,PROVENANCE ANALYSIS,SCIENTIFIC EXPERIMENTS,WORKFLOWS,None,None
215,1585,A Fast and Effective Strategy for Feature Selection in High-dimensional Datasets,Data Desconhecida,Vol. 7 No. 2 (2016),"Classification, Feature selection, High-dimensional datasets",MARIANA TASCA,ALEXANDRE PLASTINO,CELSO RIBEIRO,BIANCA ZADROZNY,None,None,None,None,UNIVERSIDADE FEDERAL FLUMINENSE,UNIVERSIDADE FEDERAL FLUMINENSE,UNIVERSIDADE FEDERAL FLUMINENSE,IBM RESEARCH,NaN,NaN,NaN,NaN,CLASSIFICATION,FEATURE SELECTION,HIGH-DIMENSIONAL DATASETS,None,None
232,1555,Information Gain Feature Selection for Multi-Label Classification,Data Desconhecida,Vol. 6 No. 1 (2015),"Classification, Data mining, Feature selection, Multi-label classification",RAFAEL B. PEREIRA,ALEXANDRE PLASTINO,BIANCA ZADROZNY,LUIZ H. C. MERSCHMANN,None,None,None,None,UNIVERSIDADE FEDERAL FLUMINENSE,UNIVERSIDADE FEDERAL FLUMINENSE,IBM RESEARCH,BRASIL,UNIVERSIDADE FEDERAL DE OURO PRETO,NaN,NaN,NaN,CLASSIFICATION,DATA MINING,FEATURE SELECTION,MULTI-LABEL CLASSIFICATION,None
263,1526,Exploring Attribute Selection in Hierarchical Classification,Data Desconhecida,Vol. 5 No. 1 (2014),"Attribute selection, Classification, Data mining, Hierarchical classification",BRUNO C. PAES,ALEXANDRE PLASTINO,ALEX A. FREITAS,None,None,None,None,None,UNIVERSIDADE FEDERAL FLUMINENSE,UNIVERSIDADE FEDERAL FLUMINENSE,UNIVERSITY OF KENT,NaN,NaN,NaN,NaN,NaN,ATTRIBUTE SELECTION,CLASSIFICATION,DATA MINING,HIERARCHICAL CLASSIFICATION,None
281,1507,A Relevance Measure for Multivalued Attributes,Data Desconhecida,Vol. 4 No. 3 (2013),"Attribute selection, Classification, Multi-relational data mining, Multivalued attributes, Relevance measures",MARIANA TASCA,BIANCA ZADROZNY,ALEXANDRE PLASTINO,None,None,None,None,None,UNIVERSIDADE FEDERAL FLUMINENSE,IBM RESEARCH,UNIVERSIDADE FEDERAL FLUMINENSE,NaN,NaN,NaN,NaN,NaN,ATTRIBUTE SELECTION,CLASSIFICATION,MULTI-RELATIONAL DATA MINING,MULTIVALUED ATTRIBUTES,RELEVANCE MEASURES
296,1466,Performance Analysis of Data Filtering in Scientific Workflows,Data Desconhecida,Vol. 4 No. 1 (2013),Scienti,JOÃO GONÇALVES,DANIEL DE OLIVEIRA,KARY OCAÑA,EDUARDO OGASAWARA,JONAS DIAS,MARTA MATTOSO,None,None,UNIVERSIDADE FEDERAL DO RIO DE JANEIRO,UNIVERSIDADE FEDERAL FLUMINENSE,UNIVERSIDADE FEDERAL DO RIO DE JANEIRO,CENTRO FEDERAL DE EDUCAÇÃO TECNOLÓGICA,UNIVERSIDADE FEDERAL DO RIO DE JANEIRO,UNIVERSIDADE FEDERAL DO RIO DE JANEIRO,NaN,NaN,SCIENTI,None,None,None,None
297,1467,Towards Recommendations for Horizontal XML Fragmentation,Data Desconhecida,Vol. 4 No. 1 (2013),"Database fragmentation design, Heuristics, Horizontal fragmentation, Xml",TATIANE LIMA DA SILVA,FERNANDA BAIÃO,JONICE DE OLIVEIRA SAMPAIO,MARTA MATTOSO,VANESSA BRAGANHOLO,None,None,None,UNIVERSIDADE FEDERAL DO RIO DE JANEIRO,UNIRIO,UNIVERSIDADE FEDERAL DO RIO DE JANEIRO,UNIVERSIDADE FEDERAL DO RIO DE JANEIRO,UNIVERSIDADE FEDERAL FLUMINENSE,NaN,NaN,NaN,DATABASE FRAGMENTATION DESIGN,HEURISTICS,HORIZONTAL FRAGMENTATION,XML,None
326,1433,Towards Querying Implicit Knowledge in XML Documents,Data Desconhecida,Vol. 3 No. 1 (2012),"Inference, Prolog, Query, Xml",DIEGO LIMA,CARLA DELGADO,LEONARDO MURTA,VANESSA BRAGANHOLO,None,None,None,None,UNIVERSIDADE FEDERAL DO RIO DE JANEIRO,UNIVERSIDADE FEDERAL DO RIO DE JANEIRO,UNIVERSIDADE FEDERAL FLUMINENSE,UNIVERSIDADE FEDERAL FLUMINENSE,NaN,NaN,NaN,NaN,INFERENCE,PROLOG,QUERY,XML,None
342,1420,Improving Lazy Attribute Selection,Data Desconhecida,Vol. 2 No. 3 (2011),"Attribute selection, Classification, Lazy learning",RAFAEL B. PEREIRA,ALEXANDRE PLASTINO,BIANCA ZADROZNY,LUIZ H. DE C. MERSCHMANN,ALEX A. FREITAS,None,None,None,UNIVERSIDADE FEDERAL FLUMINENSE,UNIVERSIDADE FEDERAL FLUMINENSE,IBM RESEARCH,UNIVERSIDADE FEDERAL DE OURO PRETO,UNIVERSITY OF KENT,NaN,NaN,NaN,ATTRIBUTE SELECTION,CLASSIFICATION,LAZY LEARNING,None,None
345,1423,Virtual Partitioning ad-hoc Queries over Distributed XML Databases,Data Desconhecida,Vol. 2 No. 3 (2011),"Xml, Distributed query processing, Virtual partitioning",CARLA RODRIGUES,VANESSA BRAGANHOLO,MARTA MATTOSO,None,None,None,None,None,UNIVERSIDADE FEDERAL DO RIO DE JANEIRO,UNIVERSIDADE FEDERAL FLUMINENSE,UNIVERSIDADE FEDERAL DO RIO DE JANEIRO,NaN,NaN,NaN,NaN,NaN,XML,DISTRIBUTED QUERY PROCESSING,VIRTUAL PARTITIONING,None,None
348,1426,Extracting new relations to improve ontology reuse,Data Desconhecida,Vol. 2 No. 3 (2011),"Aligment, Information extraction, Ontology",MIGUEL G. P. DE CARVALHO,LINAIR M. CAMPOS,VANESSA BRAGANHOLO,MARIA LUIZA M. CAMPOS,MARIA LUIZA A. CAMPOS,None,None,None,UNIVERSIDADE FEDERAL DO RIO DE JANEIRO,UNIVERSIDADE FEDERAL DO RIO DE JANEIRO,UNIVERSIDADE FEDERAL FLUMINENSE,UNIVERSIDADE FEDERAL DO RIO DE JANEIRO,UNIVERSIDADE FEDERAL FLUMINENSE,NaN,NaN,NaN,ALIGMENT,INFORMATION EXTRACTION,ONTOLOGY,None,None
353,1397,Distributed Database Research at COPPE/UFRJ,Data Desconhecida,Vol. 2 No. 2 (2011),"Database clusters, Distribution, Distributed xml query processing, Provenance",MARTA MATTOSO,VANESSA BRAGANHOLO,ALEXANDRE A. B. LIMA,LEONARDO MURTA,None,None,None,None,UNIVERSIDADE FEDERAL DO RIO DE JANEIRO,UNIVERSIDADE FEDERAL FLUMINENSE,UNIVERSIDADE FEDERAL DO RIO DE JANEIRO,UNIVERSIDADE FEDERAL FLUMINENSE,NaN,NaN,NaN,NaN,DATABASE CLUSTERS,DISTRIBUTION,DISTRIBUTED XML QUERY PROCESSING,PROVENANCE,None
377,1283,HiSP-GC: A Classification Method Based on Probabilistic Analysis of Patterns,Data Desconhecida,Vol. 1 No. 3 (2010),Classifi,LUIZ MERSCHMANN,ALEXANDRE PLASTINO,None,None,None,None,None,None,UNIVERSIDADE FEDERAL DE OURO PRETO,UNIVERSIDADE FEDERAL FLUMINENSE,NaN,NaN,NaN,NaN,NaN,NaN,CLASSIFI,None,None,None,None
379,1288,Processing Queries over Distributed XML Databases,Data Desconhecida,Vol. 1 No. 3 (2010),"Distribution, Query processing, Xml",GUILHERME FIGUEIREDO,VANESSA BRAGANHOLO,MARTA MATTOSO,None,None,None,None,None,UNIVERSIDADE FEDERAL DO RIO DE JANEIRO,UNIVERSIDADE FEDERAL FLUMINENSE,UNIVERSIDADE FEDERAL DO RIO DE JANEIRO,NaN,NaN,NaN,NaN,NaN,DISTRIBUTION,QUERY PROCESSING,XML,None,None

In [1297]:
cols = [f'instituicao_{i}' for i in range(1, 9)]

df_long = df[cols].melt(value_name='instituicao').dropna()

resultado = df_long['instituicao'].value_counts().reset_index()
resultado.columns = ['instituicao', 'count']

resultado = resultado.sort_values('count', ascending=False)

resultado

,instituicao,count
0,UNIVERSIDADE FEDERAL DE MINAS GERAIS,264
1,UNIVERSIDADE DE SÃO PAULO,200
2,UNIVERSIDADE FEDERAL DO RIO DE JANEIRO,90
3,UNIVERSIDADE FEDERAL FLUMINENSE,88
4,NO AFFILIATION DECLARED,72
5,UNIVERSIDADE FEDERAL DO CEARÁ,65
6,UNIVERSIDADE FEDERAL DE PERNAMBUCO,58
7,UNIVERSIDADE FEDERAL DO RIO GRANDE DO SUL,56
8,UNIVERSIDADE FEDERAL DE CAMPINA GRANDE,45
9,UNIVERSIDADE ESTADUAL DE CAMPINAS,39
10,UNIVERSIDADE FEDERAL DO AMAZONAS,36
11,UNIVERSIDADE FEDERAL DE GOIÁS,33
12,UNIVERSIDADE FEDERAL DE SANTA CATARINA,31
13,PUC-RIO,26
14,UNIVERSIDADE FEDERAL DE SÃO CARLOS,23
15,UNIVERSIDADE FEDERAL DO PARANÁ,22
16,INSTITUTO TECNOLÓGICO DE AERONÁUTICA,22
17,UNIVERSIDADE DE BRASÍLIA,21
18,UNIVERSIDADE FEDERAL DE OURO PRETO,19
19,FEDERAL UNIVERSITY OF CEARÁ,17
20,UNIVERSIDADE DE FORTALEZA,16
21,INSTITUTOS FEDERAIS,16
22,UNIVERSIDADE FEDERAL DE UBERLÂNDIA,16
23,FUNDAÇÃO OSWALDO CRUZ,12
24,FEDERAL UNIVERSITY OF SÃO CARLOS,12
25,BRASIL,12
26,UNIVERSIDADE FEDERAL DE SÃO JOÃO DEL REI,11
27,FEDERAL UNIVERSITY OF UBERLÂNDIA,10
28,UNIVERSIDADE FEDERAL DO RIO GRANDE,9
29,FEDERAL UNIVERSITY OF PARANÁ,8
30,FEDERAL UNIVERSITY OF FRONTEIRA SUL,7
31,UNIVERSIDADE TECNOLÓGICA FEDERAL DO PARANÁ,7
32,INPE - NATIONAL INSTITUTE FOR SPACE RESEARCH,7
33,UNIVERSITY OF STUTTGART,7
34,FEDERAL UNIVERSITY OF PARAÍBA,7
35,FEDERAL UNIVERSITY OF JUIZ DE FORA,6
36,UNIVERSITY OF LUXEMBOURG,6
37,UNIRIO,6
38,UNIVERSITY OF ALBERTA,6
42,UNIVERSIDADE FEDERAL DE ALAGOAS,5
44,IBM RESEARCH,5
43,INSTITUTO NACIONAL DE PESQUISAS ESPACIAIS,5
41,UNIVERSIDADE FEDERAL DO ESPÍRITO SANTO,5
40,UNIVERSIDADE FEDERAL DE VIÇOSA,5
39,UNIVERSITY OF FEIRA DE SANTANA,5
54,UEL,4
62,MODUL UNIVERSITY VIENNA,4
61,DEPARTMENT OF NEW MEDIA TECHNOLOGY,4
60,UNIVERSITY OF UTAH,4
59,TECHNISCHE UNIVERSITÄT DARMSTADT,4
58,CARNEGIE MELLON UNIVERSITY,4
57,DATABASES AND DISTRIBUTED SYSTEMS GROUP,4
56,UFV,4
55,INSTITUTE OF COMPUTING,4
51,DEPARTAMENTO DE INFORMÁTICA - UNIVERSIDADE FEDERAL DE VIÇOSA,4
53,INSTITUTE OF MATHEMATICS AND STATISTICS,4
52,COMPUTER SCIENCE DEPARTMENT,4
45,EMPRESA BRASILEIRA DE PESQUISA AGROPECUÁRIA,4
50,LABORATÓRIO DE SISTEMAS DE INFORMAÇÃO,4
49,GOGEO,4
48,FEDERAL UNIVERSITY OF SÃO JOÃO DEL-REI,4
47,UNIVERSIDADE PAULISTA,4
46,UNIVERSIDADE FEDERAL RURAL DO SEMI-ÁRIDO,4
75,FEDERAL UNIVERSITY OF ESPÍRITO SANTO,3
76,UNIVERSIDAD NACIONAL DE ROSARIO,3
77,CENTRO FEDERAL DE EDUCAÇÃO TECNOLÓGICA,3
82,FEDERAL INSTITUTE OF SÃO PAULO,3
79,LABORATÓRIO NACIONAL DE COMPUTAÇÃO CIENTÍFICA,3
80,UNIVERSITY OF CHILE,3
81,SENAI INNOVATION INSTITUTE FOR MINERAL TECHNOLOGIES,3
73,VIENNA UNIVERSITY OF ECONOMICS AND BUSINESS,3
74,INSTITUTE OF PARALLEL AND DISTRIBUTED SYSTEMS,3
78,SAP GERMANY,3
72,CENIDET,3
66,FEDERAL UNIVERSITY OF TECHNOLOGY - PARANÁ,3
71,INSTITUTO DE INFORMÁTICA,3
64,UNIVERSIDADE ESTADUAL DE MARINGÁ,3
65,UNIVERSITY OF BRASÍLIA,3
63,ESCOLA POLITÉCNICA DA UNIVERSIDADE DE SÃO PAULO,3
67,FEDERAL UNIVERSITY OF PIAUÍ,3
68,NATIONAL LABORATORY FOR SCIENTIFIC COMPUTING,3
69,FEDERAL UNIVERSITY OF PARA,3
70,FEDERAL UNIVERSITY OF BAHIA,3
113,INRIA AND LIRMM,2
105,DEPARTMENT OF COMPUTER SCIENCE,2
106,CONTROLADORIA GERAL DA UNIÃO,2
107,UNIVERSITY PARIS-DAUPHINE,2
108,UNIVERSITY OF KENT,2
109,PROS-UPV,2
110,UNIVERSIDAD DE CONCEPCION,2
111,SCHOOL OF ARTS,2
112,UNIVERSITÉ DE TOURS,2
118,HEWLETT PACKARD ENTERPRISE,2
114,SCIENCE AND HUMANITIES,2
115,UNIVERSITÉ DE BOURGOGNE,2
116,ETIS-CNRS-ENSEA-UNIVERSITÉ DE CERGY PONTOISE,2
117,MONTPELLIER,2
119,CNRS,2
120,VIRGINIA TECH,2
121,FRANCE,2
103,UNIVERSIDADE DO ESTADO DO RIO GRANDE DO NORTE,2
104,FEDERAL UNIVERSITY OF SANTA MARIA,2
94,AT&T LABS - RESEARCH,2
102,SOFTWARE COMPETENCE CENTER HAGENBERG,2
91,CMU,2
101,PRODABEL,2
84,UNIVERSIDADE FEDERAL DO PARÁ (UFPA),2
85,FEDERAL UNIVESITY OF CEARÁ,2
86,UERJ,2
87,LONDRINA STATE UNIVERSITY,2
88,STATE UNIVERSITY OF FEIRA DE SANTANA,2
89,UNIVERSITY OF BELGRADE,2
90,BTU COTTBUS,2
83,PROGRAMA DE PÓS-GRADUAÇÃO EM SENSORIAMENTO REMOTO (PGSER),2
92,VICTORIA UNIVERSITY OF WELLINGTON,2
100,SCIENCE AND TECHNOLOGY,2
95,UNIVERSITY OF KAISERSLAUTERN,2
96,COORDENAÇÃO DE ENSINO,2
97,UNIVERSITY OF THESSALY,2
98,CIÊNCIA E TECNOLOGIA DA PARAÍBA,2
99,UNIVERSIDADE ESTADUAL DO CEARÁ,2
93,UC-RIVERSIDE,2
208,SCIENCE AND TECHNOLOGY BAIANO,1
209,JET PROPULSION LABORATORY-NASA,1
210,UNIVERSITY OF NEW SOUTH WALES,1
211,INRIA,1
212,UNIVERSITÉ DE LYON,1
213,DALHOUSIE UNIVERSITY,1
216,FACULTY OF INFORMATION SCIENCE,1
214,ECSE - RENSSELAER POLYTECHNIC INSTITUTE,1
215,UNIVERSIDADE ESTADUAL DO NORTE DO PARANÁ,1
206,UNIVERSIDADE FEDERAL DO TRIÂNGULO MINEIRO/UNIVERSIDADE DE SÃO PAULO,1
217,RENSSELAER POLYTECHNIC INSTITUTE,1
218,INSTITUTO DE COMPUTACAO,1
219,UNIVERSIDADE FEDERAL DE SÃO JOÃO DEL RE,1
220,UNIVERSITY OF TORONTO,1
207,JAPAN,1
203,CINNECTA - PART OF MATERA,1
205,CIÊNCIA E TECNOLOGIA DO PARANÁ,1
204,UNIVERSITÈ PARIS-SACLAY,1
202,INSTITUTO NACIONAL DE PESQUISAS ESPACIAIS (INPE),1
201,UNIVERSIDADE FEDERAL DE SÃO CARLOS,1
200,CIÊNCIA E TECNOLOGIA DE SÃO PAULO,1
199,UNIVERSIDAD NACIONAL DE SAN LUIS,1
198,UNIVERSIDAD DE LA REPÚBLICA,1
222,INSTITUIÇÃO NÃO INFORMADA,1
197,DATA DOMAIN,1
196,UNIVERSITY OF APPLIED SCIENCES CHUR,1
195,NATIONAL INSTITUTE FOR SPACE RESEARCH (INPE),1
194,ISTI-CNR,1
193,CIÊNCIA E TECNOLOGIA DE SÃO PAULO - CAMPUS SÃO CARLOS,1
192,INRIA - UNIVERSITY OF NANTES,1
191,UNIVERSIDADE ESTADUAL DA PARAÍBA (UEPB),1
221,UNIVERSIDADE ESTADUAL DE PONTA GROSSA,1
232,UNIVERSITY OF MONTPELLIER,1
223,CONSIGLIO NAZIONALE DELLE RICERCHE (CNR) -ISTI,1
241,METHODIST UNIVERSITY OF PIRACICABA,1
189,LTD - RD,1
254,UNIVERSITY OF LONDRINA,1
253,LIRMM,1
252,DEPARTAMENTO DE CIÊNCIA DA COMPUTAÇÃO,1
251,DEPT. OF COMPUTER SCIENCE UNIVERSIDAD DE CHILE,1
250,GEORGIA INSTITUTE OF TECHNOLOGY,1
249,PONTIFICIA UNIVERSIDAD CATOLICA DE CHILE,1
248,INSA-LYON,1
247,UNIVERSITY OF LILLE E INRIA LILLE - NORD EUROPE,1
246,VALE INSTITUTE OF TECHNOLOGY,1
245,UNIVERSIDADE AUTÓNOMA DE LISBOA,1
244,LIST,1
243,SCHOOL FOR ENVIRONMENT AND SUSTAINABILITY,1
242,SÃO PAULO FEDERAL INSTITUTE OF EDUCATION,1
240,INSTITUTO SUPERIOR TÉCNICO/INESC-ID,1
224,UNIVERSITY OF MICHIGAN (UOFM),1
239,ZUNNIT TECHNOLOGIES,1
238,CENTER FOR EXPERIMENTAL RESEARCH IN COMPUTER SYSTEMS,1
237,INRIA E LIRMM - UNIVERSITY OF MONTPELLIER,1
236,UNIVERSIDADE FEDERAL DO MARANHÃO,1
235,DIGITRO TECNOLOGIA SA,1
234,UNIVERSITY OF ALMERIA,1
233,CHOCOLATE CLOUD,1
231,LUIZALABS,1
230,INRIA - UNIVERSITY OF MONTPELLIER,1
229,UNIVERSITY OF WESTERN ONTARIO,1
228,ESCOLA BRASILEIRA DE ADMINISTRAÇÃO PÚBLICA E DE EMPRESAS FUNDAÇÃO GETULIO VARGAS (FGV),1
227,PROGRAMA DE PÓS GRADUAÇÃO EM BIOINFORMÁTICA,1
226,UNIVERSIDADE DE SÃO PAULO/UNIVERSITÉ PARIS CITÉ,1
225,CEA,1
190,INSTITUTO AMBIENTAL E TECNOLÓGICO DA AMAZÔNIA,1
128,DEPARTMENT OF COMPUTER ENGINEERING,1
188,UNIVERSIDADE FEDERAL DE JUIZ DE FORA,1
138,INSTITUTO ATLÂNTICO,1
152,FACENS UNIVERSITY,1
151,CESAR SCHOOL,1
150,UNIFESP AND INSTITUTO TECNOLÓGICO DE AERONÁUTICA,1
149,FEDERAL UNIVERSITY OF TECHNOLOGY – PARANÁ,1
148,UNIVERSITÉ PARIS CITÉ/UNIVERSIDADE DE SÃO PAULO,1
147,FEIRA DE SANTANA HIGHER EDUCATION UNIT,1
146,DEPARTMENT OF INFORMATION SYSTEMS AND OPERATIONS,1
145,INSTITUTO DE COMPUTACIÓN,1
144,CPQD FOUNDATION,1
143,GOIANO FEDERAL INSTITUTE OF EDUCATION,1
142,COLLEGE OF ENGINEERING TRIVANDRUM,1
141,JUSBRASIL,1
140,UNIVERSIDADE FEDERAL RURAL DA AMAZÔNIA,1
139,AMARO JOSÉ DA SILVA,1
137,PONTIFICA UNIVERSIDAD CATOLICA DE CHILE,1
154,FEDERAL INSTITUTE OF PIAUÍ,1
136,LUIZ CARLOS GOMES MOREIRA AND ROSANE MANZONI MOREIRA,1
135,PETRÓLEO BRASILEIRO S.A,1
134,UNIVERSIDADE SALVADOR - UNIFACS LAUREATE\n\nHEIDELBERG UNIVERSITY,1
133,UNIVERSIDADE DE UBERLÂNDIA,1
132,FEDERAL UNIVERSITY OF TECHNOLOGY - FEDERAL UNIVERSITY OF PARANÁ,1
131,FEDERAL UNIVERSITY OF ABC,1
130,UNIVERSIDAD CATÓLICA SAN PABLO,1
129,FEDERAL UNIVERSITY OF UBERLÂNDIA / GETULIO VARGAS FOUNDATION,1
127,IMPLANTA IT SOLUTIONS LTDA,1
126,UNIVERSIDADE FEDERAL DE SÃO PAULO,1
125,DEZOO,1
124,UNIVERSIDADE DE SÃO PAULO/NORTH CAROLINA STATE UNIVERSITY,1
123,UNIVERSIDADE FEDERAL DE SANTA MARIA,1
122,ÅBO AKADEMI,1
153,UNIVERSIDADE FEDERAL DA PARAÍBA,1
155,ORACLE,1
187,UNIV. GRENOBLE ALPES CNRS,1
172,INSTITUTE FOR INFORMATION BUSINESS,1
186,MERCADO LIVRE,1
185,FEDERAL INSTITUTE OF EDUCATION,1
184,FEDERAL UNIVERSITY OF PARANÁ / FEDERAL INSTITUTE OF PARANÁ,1
183,TSUKUBA UNIVERSITY,1
182,PROGRAMA DE PÓS GRADUAÇÃO EM BIOTECNOLOGIA,1
181,NORTH CAROLINA STATE UNIVERSITY,1
180,INSTITUTO MAUÁ DE TECNOLOGIA,1
179,MANNA TEAM,1
178,PESQUISA E EXTENSÃO (COEPE),1
177,UFBA,1
176,FACULTAD DE INGENIERÍA,1
175,DUETO TECNOLOGIA LTDA,1
174,FUCAPI,1
173,INDIAN INSTITUTE OF TECHNOLOGY MADRAS,1
171,FEDERAL UNIVERSITY OF MATO GROSSO DO SUL (UFMS),1
156,FUNDAÇÃO GETÚLIO VARGAS (FGV),1
170,UNIVERSITY OF BELGRADE\n\nINDIANA UNIVERSITY,1
169,UNIVERSIDAD DE SÃO PAULO,1
168,CIÊNCIA E TECNOLOGIA TRIÂNGULO MINEIRO,1
167,UFRRJ,1
166,UNIVERSIDADE FEDERAL DE LAVRAS,1
165,UNIVERSIDADE SALVADOR - UNIFACS LAUREATE\n\nBAHIA STATE UNIVERSITY – UNEB,1
164,FEDERAL UNIVERSITY OF LAVRAS,1
163,SECRETARIA DA FAZENDA DO ESTADO DE SÃO PAULO,1
162,BRADESCO BANK S.A.,1
161,UNIFESP,1
160,FEDERAL UNIVERSIY OF CEARÁ,1
159,SÃO PAULO UNIVERSITY,1
158,UNIVERSIDADE FEDERAL DO MATO GROSSO (UFMT),1
157,NATIONAL LABORATORY OF SCIENTIFIC COMPUTING (LNCC),1
255,LIRIS,1

Alunos por Instituição

In [1288]:
df_autores_treated = autores.copy()
df_autores_treated = df_autores_treated.drop_duplicates()
df_autores_treated['inst'] = df_autores_treated['inst'].str.upper().apply(normalizar_instituicao)

In [1294]:
df_autores_treated.groupby('inst').size().reset_index(name='count') \
    .sort_values('count', ascending=False)

,inst,count
160,UNIVERSIDADE FEDERAL DE MINAS GERAIS,191
143,UNIVERSIDADE DE SÃO PAULO,166
180,UNIVERSIDADE FEDERAL DO RIO DE JANEIRO,87
102,NO AFFILIATION DECLARED,72
184,UNIVERSIDADE FEDERAL FLUMINENSE,60
174,UNIVERSIDADE FEDERAL DO CEARÁ,51
162,UNIVERSIDADE FEDERAL DE PERNAMBUCO,48
182,UNIVERSIDADE FEDERAL DO RIO GRANDE DO SUL,47
149,UNIVERSIDADE ESTADUAL DE CAMPINAS,42
156,UNIVERSIDADE FEDERAL DE CAMPINA GRANDE,42
173,UNIVERSIDADE FEDERAL DO AMAZONAS,29
163,UNIVERSIDADE FEDERAL DE SANTA CATARINA,28
113,PUC-RIO,22
157,UNIVERSIDADE FEDERAL DE GOIÁS,22
87,INSTITUTO TECNOLÓGICO DE AERONÁUTICA,22
141,UNIVERSIDADE DE BRASÍLIA,20
178,UNIVERSIDADE FEDERAL DO PARANÁ,19
161,UNIVERSIDADE FEDERAL DE OURO PRETO,18
42,FEDERAL UNIVERSITY OF CEARÁ,16
166,UNIVERSIDADE FEDERAL DE SÃO CARLOS,15
142,UNIVERSIDADE DE FORTALEZA,14
88,INSTITUTOS FEDERAIS,13
170,UNIVERSIDADE FEDERAL DE UBERLÂNDIA,11
65,FUNDAÇÃO OSWALDO CRUZ,10
181,UNIVERSIDADE FEDERAL DO RIO GRANDE,9
131,UNIFESP,9
49,FEDERAL UNIVERSITY OF PARANÁ,8
168,UNIVERSIDADE FEDERAL DE SÃO JOÃO DEL REI,8
72,INPE - NATIONAL INSTITUTE FOR SPACE RESEARCH,7
51,FEDERAL UNIVERSITY OF PARAÍBA,7
54,FEDERAL UNIVERSITY OF SÃO CARLOS,7
190,UNIVERSIDADE TECNOLÓGICA FEDERAL DO PARANÁ,7
44,FEDERAL UNIVERSITY OF FRONTEIRA SUL,6
58,FEDERAL UNIVERSITY OF UBERLÂNDIA,6
4,BRASIL,5
21,"DATABASES AND DISTRIBUTED SYSTEMS GROUP, TECHNISCHE UNIVERSITÄT DARMSTADT",5
155,UNIVERSIDADE FEDERAL DE ALAGOAS,5
85,INSTITUTO NACIONAL DE PESQUISAS ESPACIAIS,5
175,UNIVERSIDADE FEDERAL DO ESPÍRITO SANTO,5
45,FEDERAL UNIVERSITY OF JUIZ DE FORA,5
66,GOGEO,4
186,UNIVERSIDADE FEDERAL RURAL DO SEMI-ÁRIDO,4
171,UNIVERSIDADE FEDERAL DE VIÇOSA,4
55,FEDERAL UNIVERSITY OF SÃO JOÃO DEL-REI,4
100,NATIONAL LABORATORY FOR SCIENTIFIC COMPUTING,4
133,UNIRIO,4
187,UNIVERSIDADE PAULISTA,4
206,UNIVERSITY OF STUTTGART,4
33,EMPRESA BRASILEIRA DE PESQUISA AGROPECUÁRIA,4
23,DEPARTAMENTO DE INFORMÁTICA - UNIVERSIDADE FEDERAL DE VIÇOSA,4
196,UNIVERSITY OF BRASÍLIA,3
6,CARNEGIE MELLON UNIVERSITY,3
48,FEDERAL UNIVERSITY OF PARA,3
83,"INSTITUTO DE INFORMÁTICA, UNIVERSIDADE FEDERAL DE GOIÁS",3
79,"INSTITUTE OF PARALLEL AND DISTRIBUTED SYSTEMS, UNIVERSITY OF STUTTGART",3
203,UNIVERSITY OF LUXEMBOURG,3
32,EMORY UNIVERSITY,3
117,SENAI INNOVATION INSTITUTE FOR MINERAL TECHNOLOGIES,3
7,CENIDET,3
35,ESCOLA POLITÉCNICA DA UNIVERSIDADE DE SÃO PAULO,3
69,IBM RESEARCH,3
150,UNIVERSIDADE ESTADUAL DE MARINGÁ,3
92,LABORATÓRIO NACIONAL DE COMPUTAÇÃO CIENTÍFICA,3
191,UNIVERSITY OF ALBERTA,3
52,FEDERAL UNIVERSITY OF PIAUÍ,3
197,UNIVERSITY OF CHILE,3
129,UFV,3
39,FEDERAL INSTITUTE OF SÃO PAULO,3
57,FEDERAL UNIVERSITY OF TECHNOLOGY - PARANÁ,3
138,UNIVERSIDAD NACIONAL DE ROSARIO,3
198,UNIVERSITY OF FEIRA DE SANTANA,3
41,FEDERAL UNIVERSITY OF BAHIA,3
43,FEDERAL UNIVERSITY OF ESPÍRITO SANTO,3
211,UNIVERSITY PARIS-DAUPHINE,2
98,"MODUL UNIVERSITY VIENNA, DEPARTMENT OF NEW MEDIA TECHNOLOGY",2
17,CONTROLADORIA GERAL DA UNIÃO,2
14,CMU,2
110,"PROGRAMA DE PÓS-GRADUAÇÃO EM SENSORIAMENTO REMOTO (PGSER), COORDENAÇÃO DE ENSINO, PESQUISA E EXTENSÃO (COEPE), INSTITUTO NACIONAL DE PESQUISAS ESPACIAIS (INPE)",2
136,UNIVERSIDAD DE CONCEPCION,2
1,ARQUIVO DO ESTADO DE SÃO PAULO,2
10,CENTRO FEDERAL DE EDUCAÇÃO TECNOLÓGICA,2
126,UERJ,2
115,SAP GERMANY,2
221,VIRGINIA TECH,2
5,BTU COTTBUS,2
147,UNIVERSIDADE DO ESTADO DO RIO GRANDE DO NORTE,2
152,UNIVERSIDADE ESTADUAL DO CEARÁ,2
125,UEL,2
119,STATE UNIVERSITY OF FEIRA DE SANTANA,2
93,LONDRINA STATE UNIVERSITY,2
112,PROS-UPV,2
209,UNIVERSITY OF UTAH,2
68,HEWLETT PACKARD ENTERPRISE,2
26,"DEPARTMENT OF NEW MEDIA TECHNOLOGY, MODUL UNIVERSITY VIENNA",2
53,FEDERAL UNIVERSITY OF SANTA MARIA,2
207,UNIVERSITY OF THESSALY,2
194,UNIVERSITY OF BELGRADE,2
179,UNIVERSIDADE FEDERAL DO PARÁ (UFPA),2
61,FEDERAL UNIVESITY OF CEARÁ,2
189,UNIVERSIDADE SALVADOR - UNIFACS LAUREATE\n\nHEIDELBERG UNIVERSITY,1
154,UNIVERSIDADE FEDERAL DA PARAÍBA,1
153,UNIVERSIDADE ESTADUAL DO NORTE DO PARANÁ,1
188,UNIVERSIDADE SALVADOR - UNIFACS LAUREATE\n\nBAHIA STATE UNIVERSITY – UNEB,1
151,UNIVERSIDADE ESTADUAL DE PONTA GROSSA,1
201,UNIVERSITY OF LILLE E INRIA LILLE - NORD EUROPE,1
200,UNIVERSITY OF KENT,1
192,UNIVERSITY OF ALMERIA,1
199,UNIVERSITY OF KAISERSLAUTERN,1
148,UNIVERSIDADE ESTADUAL DA PARAÍBA (UEPB),1
185,UNIVERSIDADE FEDERAL RURAL DA AMAZÔNIA,1
193,"UNIVERSITY OF APPLIED SCIENCES CHUR, FACULTY OF INFORMATION SCIENCE",1
146,UNIVERSIDADE DE UBERLÂNDIA,1
145,UNIVERSIDADE DE SÃO PAULO/UNIVERSITÉ PARIS CITÉ,1
144,UNIVERSIDADE DE SÃO PAULO/NORTH CAROLINA STATE UNIVERSITY,1
222,ZUNNIT TECHNOLOGIES,1
195,UNIVERSITY OF BELGRADE\n\nINDIANA UNIVERSITY,1
202,"UNIVERSITY OF LONDRINA, UEL",1
210,UNIVERSITY OF WESTERN ONTARIO,1
220,"VIENNA UNIVERSITY OF ECONOMICS AND BUSINESS, INSTITUTE FOR INFORMATION BUSINESS",1
172,"UNIVERSIDADE FEDERAL DE VIÇOSA, MANNA TEAM",1
208,UNIVERSITY OF TORONTO,1
212,"UNIVERSITÈ PARIS-SACLAY, CEA, LIST",1
169,UNIVERSIDADE FEDERAL DE SÃO PAULO,1
213,UNIVERSITÉ DE BOURGOGNE,1
167,UNIVERSIDADE FEDERAL DE SÃO JOÃO DEL RE,1
176,UNIVERSIDADE FEDERAL DO MARANHÃO,1
214,"UNIVERSITÉ DE LYON, CNRS, INSA-LYON, LIRIS, FRANCE",1
215,UNIVERSITÉ DE TOURS,1
165,UNIVERSIDADE FEDERAL DE SÃO CARLOS,1
164,UNIVERSIDADE FEDERAL DE SANTA MARIA,1
177,UNIVERSIDADE FEDERAL DO MATO GROSSO (UFMT),1
216,UNIVERSITÉ PARIS CITÉ/UNIVERSIDADE DE SÃO PAULO,1
217,VALE INSTITUTE OF TECHNOLOGY,1
218,VICTORIA UNIVERSITY OF WELLINGTON,1
159,UNIVERSIDADE FEDERAL DE LAVRAS,1
158,UNIVERSIDADE FEDERAL DE JUIZ DE FORA,1
205,UNIVERSITY OF NEW SOUTH WALES,1
204,"UNIVERSITY OF MICHIGAN (UOFM), SCHOOL FOR ENVIRONMENT AND SUSTAINABILITY",1
219,VIENNA UNIVERSITY OF ECONOMICS AND BUSINESS,1
183,UNIVERSIDADE FEDERAL DO TRIÂNGULO MINEIRO/UNIVERSIDADE DE SÃO PAULO,1
0,AMARO JOSÉ DA SILVA,1
140,UNIVERSIDADE AUTÓNOMA DE LISBOA,1
31,ECSE - RENSSELAER POLYTECHNIC INSTITUTE,1
36,ETIS-CNRS-ENSEA-UNIVERSITÉ DE CERGY PONTOISE,1
37,"FEDERAL INSTITUTE OF EDUCATION, SCIENCE AND TECHNOLOGY BAIANO",1
38,FEDERAL INSTITUTE OF PIAUÍ,1
40,FEDERAL UNIVERSITY OF ABC,1
46,FEDERAL UNIVERSITY OF LAVRAS,1
47,FEDERAL UNIVERSITY OF MATO GROSSO DO SUL (UFMS),1
50,FEDERAL UNIVERSITY OF PARANÁ / FEDERAL INSTITUTE OF PARANÁ,1
56,FEDERAL UNIVERSITY OF TECHNOLOGY - FEDERAL UNIVERSITY OF PARANÁ,1
59,FEDERAL UNIVERSITY OF UBERLÂNDIA / GETULIO VARGAS FOUNDATION,1
60,FEDERAL UNIVERSIY OF CEARÁ,1
62,FEIRA DE SANTANA HIGHER EDUCATION UNIT,1
63,FUCAPI,1
64,FUNDAÇÃO GETÚLIO VARGAS (FGV),1
67,"GOIANO FEDERAL INSTITUTE OF EDUCATION, SCIENCE AND TECHNOLOGY",1
70,IMPLANTA IT SOLUTIONS LTDA,1
71,INDIAN INSTITUTE OF TECHNOLOGY MADRAS,1
73,INRIA - UNIVERSITY OF MONTPELLIER,1
34,ESCOLA BRASILEIRA DE ADMINISTRAÇÃO PÚBLICA E DE EMPRESAS FUNDAÇÃO GETULIO VARGAS (FGV),1
30,DUETO TECNOLOGIA LTDA,1
75,"INRIA AND LIRMM, MONTPELLIER",1
29,DIGITRO TECNOLOGIA SA,1
2,AT&T LABS - RESEARCH,1
3,BRADESCO BANK S.A.,1
8,"CENTER FOR EXPERIMENTAL RESEARCH IN COMPUTER SYSTEMS, GEORGIA INSTITUTE OF TECHNOLOGY",1
9,"CENTER OF MATHEMATICS, COMPUTING AND COGNITION, FEDERAL UNIVERSITY OF ABC",1
11,CESAR SCHOOL,1
12,CHOCOLATE CLOUD,1
13,CINNECTA - PART OF MATERA,1
15,COLLEGE OF ENGINEERING TRIVANDRUM,1
16,CONSIGLIO NAZIONALE DELLE RICERCHE (CNR) -ISTI,1
18,CPQD FOUNDATION,1
19,DALHOUSIE UNIVERSITY,1
20,DATA DOMAIN,1
22,"DEPARTAMENTO DE CIÊNCIA DA COMPUTAÇÃO, UNIVERSIDADE FEDERAL DE SÃO JOÃO DEL REI",1
24,"DEPARTMENT OF COMPUTER ENGINEERING, FACENS UNIVERSITY",1
25,"DEPARTMENT OF INFORMATION SYSTEMS AND OPERATIONS, VIENNA UNIVERSITY OF ECONOMICS AND BUSINESS",1
27,DEPT. OF COMPUTER SCIENCE UNIVERSIDAD DE CHILE,1
28,"DEZOO, UNIVERSIDADE FEDERAL DE SÃO JOÃO DEL REI",1
74,INRIA - UNIVERSITY OF NANTES,1
76,INRIA E LIRMM - UNIVERSITY OF MONTPELLIER,1
139,UNIVERSIDAD NACIONAL DE SAN LUIS,1
107,PONTIFICIA UNIVERSIDAD CATOLICA DE CHILE,1
109,"PROGRAMA DE PÓS GRADUAÇÃO EM BIOTECNOLOGIA, UNIVERSIDADE FEDERAL DE SÃO JOÃO DEL REI",1
111,"PROGRAMA DE PÓS-GRADUAÇÃO EM SENSORIAMENTO REMOTO (PGSER), COORDENAÇÃO DE ENSINO, PESQUISA E EXTENSÃO (COEPE), INSTITUTO NACIONAL DE PESQUISAS ESPACIAIS (INPE); DIVISÃO DE OBSERVAÇÃO DA TERRA E GEOINFORMÁTICA (DIOTG), COORDENAÇÃO GERAL DE CIÊNCIAS DA TERRA (CG-CT)",1
114,RENSSELAER POLYTECHNIC INSTITUTE,1
116,SECRETARIA DA FAZENDA DO ESTADO DE SÃO PAULO,1
118,SOFTWARE COMPETENCE CENTER HAGENBERG,1
120,"SÃO PAULO FEDERAL INSTITUTE OF EDUCATION, SCIENCE AND TECHNOLOGY",1
121,"SÃO PAULO STATE UNIVERSITY (UNESP), SCHOOL OF SCIENCES AND ENGINEERING, TUPÃ",1
122,SÃO PAULO UNIVERSITY,1
123,"TSUKUBA UNIVERSITY, JAPAN",1
124,UC-RIVERSIDE,1
127,UFBA,1
128,UFRRJ,1
130,"UFV, PRODABEL",1
132,UNIFESP AND INSTITUTO TECNOLÓGICO DE AERONÁUTICA,1
134,UNIV. GRENOBLE ALPES CNRS,1
135,UNIVERSIDAD CATÓLICA SAN PABLO,1
137,UNIVERSIDAD DE SÃO PAULO,1
108,PRODABEL,1
106,PONTIFICA UNIVERSIDAD CATOLICA DE CHILE,1
77,"INRIA, UNIVERSITY OF MONTPELLIER, CNRS, LIRMM, FRANCE",1
105,PETRÓLEO BRASILEIRO S.A,1
78,INSTITUIÇÃO NÃO INFORMADA,1
80,INSTITUTO AMBIENTAL E TECNOLÓGICO DA AMAZÔNIA,1
81,INSTITUTO ATLÂNTICO,1
82,"INSTITUTO DE COMPUTACIÓN, FACULTAD DE INGENIERÍA, UNIVERSIDAD DE LA REPÚBLICA",1
84,INSTITUTO MAUÁ DE TECNOLOGIA,1
86,INSTITUTO SUPERIOR TÉCNICO/INESC-ID,1
89,ISTI-CNR,1
90,JET PROPULSION LABORATORY-NASA,1
91,JUSBRASIL,1
94,LUIZ CARLOS GOMES MOREIRA AND ROSANE MANZONI MOREIRA,1
95,LUIZALABS,1
96,MERCADO LIVRE,1
97,METHODIST UNIVERSITY OF PIRACICABA,1
99,NATIONAL INSTITUTE FOR SPACE RESEARCH (INPE),1
101,NATIONAL LABORATORY OF SCIENTIFIC COMPUTING (LNCC),1
103,NORTH CAROLINA STATE UNIVERSITY,1
104,ORACLE,1
223,ÅBO AKADEMI,1

In [1310]:
!pip3 install openpyxl

import openpyxl

df.to_excel('teste.xlsx')

Collecting openpyxl
  Obtaining dependency information for openpyxl from https://files.pythonhosted.org/packages/c0/da/977ded879c29cbd04de313843e76868e6e13408a94ed6b987245dc7c8506/openpyxl-3.1.5-py2.py3-none-any.whl.metadata
  Downloading openpyxl-3.1.5-py2.py3-none-any.whl.metadata (2.5 kB)
Collecting et-xmlfile (from openpyxl)
  Obtaining dependency information for et-xmlfile from https://files.pythonhosted.org/packages/c1/8b/5fe2cc11fee489817272089c4203e679c63b570a5aaeb18d852ae3cbba6a/et_xmlfile-2.0.0-py3-none-any.whl.metadata
  Downloading et_xmlfile-2.0.0-py3-none-any.whl.metadata (2.7 kB)
Downloading openpyxl-3.1.5-py2.py3-none-any.whl (250 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 250.9/250.9 kB 1.8 MB/s eta 0:00:00a 0:00:01
Downloading et_xmlfile-2.0.0-py3-none-any.whl (18 kB)
Installing collected packages: et-xmlfile, openpyxl
Successfully installed et-xmlfile-2.0.0 openpyxl-3.1.5

[notice] A new release of pip is available: 23.2.1 -> 26.0.1
[notice] To update, run: pip install --upgrade pip