In [56]:
import pandas as pd

In [57]:
import re
import unicodedata



def normalizar_instituicao(nome):

    mapeamento = [
        (r"(FLUMIN|UFF|INFES/UFF|IC/UFF|PPGCI/UFF)",
         "Universidade Federal Fluminense"),

        (r"(SAO PAULO|USP|ICMC|POLITECNICA|EACH|UNIVERSITY OF SÃO PAULO)",
         "Universidade de São Paulo"),

        (r"(MINAS GERAIS|UFMG|BIOINFORMATICA|DCC/UFMG)",
         "Universidade Federal de Minas Gerais"),

        (r"(RIO DE JANEIRO|UFRJ|COPPE|PPGI/UFRJ|BNDES|IBCCF|PPGEN|CISI/COPPE)",
         "Universidade Federal do Rio de Janeiro"),

        (r"(CAMPINA GRANDE|UFCG|CAMINA GRANDE)",
         "Universidade Federal de Campina Grande"),

        (r"(CAMPINAS|UNICAMP|CEPAGRI)",
         "Universidade Estadual de Campinas"),

        (r"(CEARA|UFC)",
         "Universidade Federal do Ceará"),

        (r"(PERNAMBUCO|UFPE|CIN/UFPE|UFRPE|AGRESTE)",
         "Universidade Federal de Pernambuco"),

        (r"(SAO CARLOS|UFSCAR)",
         "Universidade Federal de São Carlos"),

        (r"(PUC RIO|PONTIFICAL CATHOLIC UNIVERSITY OF RIO DE JANEIRO)",
         "Pontifícia Universidade Católica do Rio de Janeiro"),

        (r"(GOIAS|UFG)",
         "Universidade Federal de Goiás"),

        (r"(PARANA|UFPR)",
         "Universidade Federal do Paraná"),

        (r"(UBERLANDIA|UFU)",
         "Universidade Federal de Uberlândia"),

        (r"(OURO PRETO|UFOP)",
         "Universidade Federal de Ouro Preto"),

        (r"(SANTA CATARINA|UFSC)",
         "Universidade Federal de Santa Catarina"),

        (r"(RIO GRANDE DO SUL|UFRGS)",
         "Universidade Federal do Rio Grande do Sul"),

        (r"(AMAZONAS|UFAM)",
         "Universidade Federal do Amazonas"),

        (r"(BRASILIA|UNB)",
         "Universidade de Brasília"),

        (r"(SAO JOAO DEL REI|UFSJ)",
         "Universidade Federal de São João Del Rei"),

        (r"(FORTALEZA|UNIFOR)",
         "Universidade de Fortaleza"),

        (r"(INSTITUTO FEDERAL|IFSP|IFMG|IFPR|IFNMG|IFPB|IFRS|IFSUL|IF SUDOESTE)",
         "Institutos Federais"),

        (r"(CEFET)",
         "Centro Federal de Educação Tecnológica"),

        (r"(UTFPR|TECHNOLOGY PARANA)",
         "Universidade Tecnológica Federal do Paraná"),

        (r"(AERONAUTICA|ITA)",
         "Instituto Tecnológico de Aeronáutica"),

        (r"(FIOCRUZ|OSWALDO CRUZ)",
         "Fundação Oswaldo Cruz"),

        (r"(EMBRAPA)",
         "Empresa Brasileira de Pesquisa Agropecuária"),

        (r"(IBM)",
         "IBM Research"),

        (r"(JUSBRASIL)",
         "Jusbrasil"),

        (r"(NO AFFILIATION DECLARED	|NOT INFORMED)",
         "Sem Afiliação"),

        (r"(BRAZIL)",
         "BRASIL")
    ]

    if pd.isna(nome):
        return None

    for padrao, nome_padrao in mapeamento:
        if re.search(padrao, nome):
            return nome_padrao.upper()

    return nome

In [58]:
df = pd.read_json(
    'C:/repository/TCC/data/raw/dados_artigos2.json')

In [59]:
pd.set_option('display.max_rows', None)
pd.set_option('display.max_columns', None)
pd.set_option('display.width', None)
pd.set_option('display.max_colwidth', None)

Explode nos autores

In [60]:
df_autores = df.explode('autores')

autores = pd.json_normalize(df_autores['autores'])

instituicoes = autores['inst']

Autores

In [61]:
df['autores'] = autores.groupby(level=0).agg({'nome': lambda x: ', '.join(x)})

# Separar os autores em colunas distintas
df['autor_1'] = df['autores'].str.split(',').str[0].str.strip().str.upper().fillna(None)
df['autor_2'] = df['autores'].str.split(',').str[1].str.strip().str.upper().fillna(None)
df['autor_3'] = df['autores'].str.split(',').str[2].str.strip().str.upper().fillna(None)
df['autor_4'] = df['autores'].str.split(',').str[3].str.strip().str.upper().fillna(None)
df['autor_5'] = df['autores'].str.split(',').str[4].str.strip().str.upper().fillna(None)
df['autor_6'] = df['autores'].str.split(',').str[5].str.strip().str.upper().fillna(None)
df['autor_7'] = df['autores'].str.split(',').str[6].str.strip().str.upper().fillna(None)
df['autor_8'] = df['autores'].str.split(',').str[7].str.strip().str.upper().fillna(None)

Instituições

In [62]:
df['instituicoes'] = autores.groupby(level=0).agg({'inst': lambda x: ', '.join(x)})

In [63]:
df.head(2)

,titulo,data,doi,volume,autores,keywords,url,autor_1,autor_2,autor_3,autor_4,autor_5,autor_6,autor_7,autor_8,instituicoes
0,Analysis of Expenses from Brazilian Federal Deputies between 2015 and 2018,Data Desconhecida,10.5753/jidm.2025.3383,Vol. 16 No. 1 (2025),"Felippe Pires Ferreira, Ilan S. G. de Figueiredo, Larissa R. Teixeira, William Zaniboni Silva, Caetano Traina Junior, Cristina Dutra de Aguiar, Robson L. F. Cordeiro","[Analysis of expenses, Public expenses, Brazilian deputies, Outliers]",https://journals-sol.sbc.org.br/index.php/jidm/article/view/3383,FELIPPE PIRES FERREIRA,ILAN S. G. DE FIGUEIREDO,LARISSA R. TEIXEIRA,WILLIAM ZANIBONI SILVA,CAETANO TRAINA JUNIOR,CRISTINA DUTRA DE AGUIAR,ROBSON L. F. CORDEIRO,None,"Universidade de São Paulo, Universidade de São Paulo, Universidade de São Paulo, Universidade de São Paulo, Universidade de São Paulo, Universidade de São Paulo, Carnegie Mellon University"
1,Exploratory Analysis of Microdata from the National High School Exam - Enem: Performance and Specificities of the Participants,Data Desconhecida,10.5753/jidm.2025.3657,Vol. 16 No. 1 (2025),"João Augusto Fernandes Barbosa, Robson Leonardo Ferreira Cordeiro","[Enem, Disability, Exploratory data analysis, Education, Performance]",https://journals-sol.sbc.org.br/index.php/jidm/article/view/3657,JOÃO AUGUSTO FERNANDES BARBOSA,ROBSON LEONARDO FERREIRA CORDEIRO,None,None,None,None,None,None,"University of São Paulo, Carnegie Mellon University"

In [64]:
df['instituicoes'] = autores.groupby(level=0)['inst'].agg(
    lambda x: '; '.join(x.astype(str).str.replace(',', '', regex=False)))

df['instituicoes'] = df['instituicoes'].fillna('') \
    .str.replace('Brazil', '', regex=False, case=False) \
    .str.replace('Brasil', '', regex=False, case=False)

df['instituicao_1'] = df['instituicoes'].str.split(
    ';').str[0].str.strip().str.upper().fillna(None)
df['instituicao_2'] = df['instituicoes'].str.split(
    ';').str[1].str.strip().str.upper().fillna(None)
df['instituicao_3'] = df['instituicoes'].str.split(
    ';').str[2].str.strip().str.upper().fillna(None)
df['instituicao_4'] = df['instituicoes'].str.split(
    ';').str[3].str.strip().str.upper().fillna(None)
df['instituicao_5'] = df['instituicoes'].str.split(
    ';').str[4].str.strip().str.upper().fillna(None)
df['instituicao_6'] = df['instituicoes'].str.split(
    ';').str[5].str.strip().str.upper().fillna(None)
df['instituicao_7'] = df['instituicoes'].str.split(
    ';').str[6].str.strip().str.upper().fillna(None)
df['instituicao_8'] = df['instituicoes'].str.split(
    ';').str[7].str.strip().str.upper().fillna(None)

Criar ID

In [65]:
df['id'] = df['url'].str.split('/').str[-1].str.replace('.html', '', regex=False)

In [66]:
# Reordenar as colunas para colocar o ID no início
colunas = ['id'] + [col for col in df.columns if col != 'id']
df = df[colunas]

In [67]:
df = df.drop(columns=['autores', 'url', 'doi', 'instituicoes']).reset_index(drop=True)

In [68]:
df.head(2)

,id,titulo,data,volume,keywords,autor_1,autor_2,autor_3,autor_4,autor_5,autor_6,autor_7,autor_8,instituicao_1,instituicao_2,instituicao_3,instituicao_4,instituicao_5,instituicao_6,instituicao_7,instituicao_8
0,3383,Analysis of Expenses from Brazilian Federal Deputies between 2015 and 2018,Data Desconhecida,Vol. 16 No. 1 (2025),"[Analysis of expenses, Public expenses, Brazilian deputies, Outliers]",FELIPPE PIRES FERREIRA,ILAN S. G. DE FIGUEIREDO,LARISSA R. TEIXEIRA,WILLIAM ZANIBONI SILVA,CAETANO TRAINA JUNIOR,CRISTINA DUTRA DE AGUIAR,ROBSON L. F. CORDEIRO,None,UNIVERSIDADE DE SÃO PAULO,UNIVERSIDADE DE SÃO PAULO,UNIVERSIDADE DE SÃO PAULO,UNIVERSIDADE DE SÃO PAULO,UNIVERSIDADE DE SÃO PAULO,UNIVERSIDADE DE SÃO PAULO,CARNEGIE MELLON UNIVERSITY,None
1,3657,Exploratory Analysis of Microdata from the National High School Exam - Enem: Performance and Specificities of the Participants,Data Desconhecida,Vol. 16 No. 1 (2025),"[Enem, Disability, Exploratory data analysis, Education, Performance]",JOÃO AUGUSTO FERNANDES BARBOSA,ROBSON LEONARDO FERREIRA CORDEIRO,None,None,None,None,None,None,UNIVERSITY OF SÃO PAULO,CARNEGIE MELLON UNIVERSITY,None,None,None,None,None,None

Keywords

In [69]:
keywords = df.explode('keywords')

df["keywords"] = (
    keywords.groupby(level=0)
            .agg({'keywords': lambda x: ', '.join(x.dropna().astype(str))})
)


# Separar as palavras-chave em colunas distintas
df['keyword_1'] = df['keywords'].str.split(',').str[0].str.strip().str.upper().fillna(None)
df['keyword_2'] = df['keywords'].str.split(',').str[1].str.strip().str.upper().fillna(None)
df['keyword_3'] = df['keywords'].str.split(',').str[2].str.strip().str.upper().fillna(None)
df['keyword_4'] = df['keywords'].str.split(',').str[3].str.strip().str.upper().fillna(None)
df['keyword_5'] = df['keywords'].str.split(',').str[4].str.strip().str.upper().fillna(None)

Padronizar nomes

In [70]:
# dcols = [f'instituicao_{i}' for i in range(1, 9)]

# df[cols] = df[cols].apply(lambda col: col.apply(normalizar_instituicao))

### VALIDAR

In [71]:
cols = [f'instituicao_{i}' for i in range(1, 9)]

df_filtrado = df[
    df[cols].apply(
        lambda col: col.str.contains('FLUMINENSE', case=False, na=False)
    ).any(axis=1)
]

df_filtrado

,id,titulo,data,volume,keywords,autor_1,autor_2,autor_3,autor_4,autor_5,autor_6,autor_7,autor_8,instituicao_1,instituicao_2,instituicao_3,instituicao_4,instituicao_5,instituicao_6,instituicao_7,instituicao_8,keyword_1,keyword_2,keyword_3,keyword_4,keyword_5
18,4361,Exploring Evolutionary Patterns: A Jupyter Notebook for Discovering Frequent Subtrees in Phylogenetic Tree Databases,Data Desconhecida,Vol. 16 No. 1 (2025),"Phylogenetics, Frequent subtrees, Bioinformatics, Workflows",JOÃO VITOR MORAES,CAMILA FERRARI,ISABEL ROSSETI,DANIEL DE OLIVEIRA,None,None,None,None,UNIVERSIDADE FEDERAL FLUMINENSE,UNIVERSIDADE FEDERAL FLUMINENSE,UNIVERSIDADE FEDERAL FLUMINENSE,UNIVERSIDADE FEDERAL FLUMINENSE,None,None,None,None,PHYLOGENETICS,FREQUENT SUBTREES,BIOINFORMATICS,WORKFLOWS,None
59,3189,Hurricane: a Dataflow-oriented Data Service for Smart Cities Applications,Data Desconhecida,Vol. 14 No. 1 (2023),"Smart cities, Data management, Data integration",MAICON BANNI,MARIA LUIZA FALCI,ISABEL ROSSETI,DANIEL DE OLIVEIRA,None,None,None,None,UNIVERSIDADE FEDERAL FLUMINENSE,UNIVERSIDADE FEDERAL FLUMINENSE,UNIVERSIDADE FEDERAL FLUMINENSE,UNIVERSIDADE FEDERAL FLUMINENSE,None,None,None,None,SMART CITIES,DATA MANAGEMENT,DATA INTEGRATION,None,None
62,3233,ORBITER: a Lightweight Framework for Automatic Deployment of Big Data Applications on Serverless Architectures,Data Desconhecida,Vol. 14 No. 2 (2023),"Serverless, Faas, Big data applications",JOÃO LOUREIRO,JOSÉ MARIA MONTEIRO,MARCOS BEDO,DANIEL DE OLIVEIRA,None,None,None,None,UNIVERSIDADE FEDERAL FLUMINENSE,UNIVERSIDADE FEDERAL DO CEARÁ,UNIVERSIDADE FEDERAL FLUMINENSE,UNIVERSIDADE FEDERAL FLUMINENSE,None,None,None,None,SERVERLESS,FAAS,BIG DATA APPLICATIONS,None,None
66,2564,Sentiment Analysis in Tweets: Exploring Instance-based Transfer Learning for Dataset Enrichment,Data Desconhecida,Vol. 13 No. 6 (2022),"Machine learning, Sentiment analysis, Supervised learning, Transfer learning, Twitter",ELISEU GUIMARÃES,DANIELA VIANNA,ALINE PAES,ALEXANDRE PLASTINO,None,None,None,None,UNIVERSIDADE FEDERAL FLUMINENSE / UNIVERSIDADE FEDERAL DO AMAZONAS,UNIVERSIDADE FEDERAL DO AMAZONAS / JUS,UNIVERSIDADE FEDERAL FLUMINENSE,UNIVERSIDADE FEDERAL FLUMINENSE,None,None,None,None,MACHINE LEARNING,SENTIMENT ANALYSIS,SUPERVISED LEARNING,TRANSFER LEARNING,TWITTER
71,2544,Capturing Provenance from Deep Learning Applications Using Keras-Prov and Colab: a Practical Approach,Data Desconhecida,Vol. 13 No. 5 (2022),"Deep learning, Metadata, Provenance",DÉBORA PINA,LILIANE KUNSTMANN,FELIPE BEVILAQUA,ISABELA SIQUEIRA,ALAN LYRA,DANIEL DE OLIVEIRA,MARTA MATTOSO,None,COPPE/FEDERAL UNIVERSITY OF RIO DE JANEIRO,COPPE/FEDERAL UNIVERSITY OF RIO DE JANEIRO,COPPE/FEDERAL UNIVERSITY OF RIO DE JANEIRO,COPPE/FEDERAL UNIVERSITY OF RIO DE JANEIRO,COPPE/FEDERAL UNIVERSITY OF RIO DE JANEIRO,FLUMINENSE FEDERAL UNIVERSITY,COPPE/FEDERAL UNIVERSITY OF RIO DE JANEIRO,None,DEEP LEARNING,METADATA,PROVENANCE,None,None
74,2059,P+RProv: Prospective+Retrospective Provenance Graphs of Python Scripts,Data Desconhecida,Vol. 13 No. 4 (2022),"Diagrams, Prospective provenance, Provenance visualization, Scripts",VITOR GAMA LEMOS,JOÃO FELIPE PIMENTEL,BRUNO ERBISTI,VANESSA BRAGANHOLO,None,None,None,None,UNIVERSIDADE FEDERAL FLUMINENSE,UNIVERSIDADE FEDERAL FLUMINENSE,UNIVERSIDADE FEDERAL FLUMINENSE,UNIVERSIDADE FEDERAL FLUMINENSE,None,None,None,None,DIAGRAMS,PROSPECTIVE PROVENANCE,PROVENANCE VISUALIZATION,SCRIPTS,None
80,2513,Beyond Click-and-View: a Comparative Study of Data Management Approaches for Interactive Visualization,Data Desconhecida,Vol. 13 No. 3 (2022),"Interactive vis, Database evaluation",LORENNA CHRIST'NA NASCIMENTO,RODOLFO P. CHAGAS,MARCOS LAGE,DANIEL DE OLIVEIRA,None,None,None,None,UNIVERSIDADE FEDERAL FLUMINENSE,UNIVERSIDADE FEDERAL FLUMINENSE,UNIVERSIDADE FEDERAL FLUMINENSE,UNIVERSIDADE FEDERAL FLUMINENSE,None,None,None,None,INTERACTIVE VIS,DATABASE EVALUATION,None,None,None
90,2435,A Framework to Compute Entity Relatedness in Large RDF Knowledge Bases,Data Desconhecida,Vol. 13 No. 2 (2022),"Entity relatedness, Rdf graph, Path search strategy, Entity similarity, Path ranking, Dbpedia, Spark",JAVIER GUILLOT JIMÉNEZ,LUIZ ANDRÉ P. PAES LEME,YENIER TORRES IZQUIERDO,ANGELO BATISTA NEVES,MARCO A. CASANOVA,None,None,None,PUC-RIO,FEDERAL FLUMINENSE UNIVERSITY,PUC-RIO,PUC-RIO,PUC-RIO,None,None,None,ENTITY RELATEDNESS,RDF GRAPH,PATH SEARCH STRATEGY,ENTITY SIMILARITY,PATH RANKING
102,2355,PolRoute-DS: a Crime Dataset for Optimization-based Police Patrol Routing,Data Desconhecida,Vol. 13 No. 1 (2022),"Crime dataset, Predictive policing, Police routing",BRUNO CUNHA SÁ,GUSTAVO MULLER,MAICON BANNI,WAGNER SANTOS,MARCOS LAGE,ISABEL ROSSETI,YURI FROTA,DANIEL DE OLIVEIRA,FLUMINENSE FEDERAL UNIVERSITY,FLUMINENSE FEDERAL UNIVERSITY,FLUMINENSE FEDERAL UNIVERSITY,FLUMINENSE FEDERAL UNIVERSITY / POLÍCIA MILITAR DO ESTADO DO RIO DE JANEIRO,FLUMINENSE FEDERAL UNIVERSITY,FLUMINENSE FEDERAL UNIVERSITY,FLUMINENSE FEDERAL UNIVERSITY,FLUMINENSE FEDERAL UNIVERSITY,CRIME DATASET,PREDICTIVE POLICING,POLICE ROUTING,None,None
106,1924,Online Deep Learning Hyperparameter Tuning based on Provenance Analysis,Data Desconhecida,Vol. 12 No. 5 (2021),"Deep learning, Provenance, Hyperparameter tuning",LILIANE KUNSTMANN,DÉBORA PINA,FILIPE SILVA,ALINE PAES,PATRICK VALDURIEZ,DANIEL DE OLIVEIRA,MARTA MATTOSO,None,FEDERAL UNIVERSITY OF RIO DE JANEIRO,FEDERAL UNIVERSITY OF RIO DE JANEIRO,FEDERAL UNIVERSITY OF RIO DE JANEIRO,FLUMINENSE FEDERAL UNIVERSITY,INRIA - UNIVERSITY OF MONTPELLIER,FLUMINENSE FEDERAL UNIVERSITY,FEDERAL UNIVERSITY OF RIO DE JANEIRO,None,DEEP LEARNING,PROVENANCE,HYPERPARAMETER TUNING,None,None
107,1923,Multimodal Provenance-based Analysis of Collaboration in Business Processes,Data Desconhecida,Vol. 12 No. 5 (2021),"Multimodal data provenance, Provenance data, Business process data",MARIA LUIZA FALCI,ANDRÉA MAGALHÃES,ALINE PAES,VANESSA BRAGANHOLO,DANIEL DE OLIVEIRA,None,None,None,UNIVERSIDADE FEDERAL FLUMINENSE,UNIVERSIDADE FEDERAL FLUMINENSE,UNIVERSIDADE FEDERAL FLUMINENSE,UNIVERSIDADE FEDERAL FLUMINENSE,UNIVERSIDADE FEDERAL FLUMINENSE,None,None,None,MULTIMODAL DATA PROVENANCE,PROVENANCE DATA,BUSINESS PROCESS DATA,None,None
121,1968,Evaluating Temporal Bias in Time Series Event Detection Methods,Data Desconhecida,Vol. 12 No. 3 (2021),"Event detection, Time series, Benchmarking, Temporal bias",LUCIANA ESCOBAR,REBECCA SALLES,JANIO LIMA,CRISTIANE GEA,LAIS BARONI,ARTUR ZIVIANI,PAULO PIRES,FLAVIA DELICATO,FEDERAL CENTER OF TECHNOLOGICAL EDUCATION OF RIO DE JANEIRO,FEDERAL CENTER OF TECHNOLOGICAL EDUCATION OF RIO DE JANEIRO,FEDERAL CENTER OF TECHNOLOGICAL EDUCATION OF RIO DE JANEIRO,FEDERAL CENTER OF TECHNOLOGICAL EDUCATION OF RIO DE JANEIRO,FEDERAL CENTER OF TECHNOLOGICAL EDUCATION OF RIO DE JANEIRO,LABORATÓRIO NACIONAL DE COMPUTAÇÃO CIENTÍFICA,UNIVERSIDADE FEDERAL FLUMINENSE,UNIVERSIDADE FEDERAL FLUMINENSE,EVENT DETECTION,TIME SERIES,BENCHMARKING,TEMPORAL BIAS,None
124,1917,An empirical assessment of quality metrics for diversified similarity searching,Data Desconhecida,Vol. 12 No. 3 (2021),"Metric spaces, Diversified similarity searching, Result diversification, Similarity searching",CAMILA R. LOPES,LÚCIO F. D. SANTOS,DANIEL L. JASBICK,DANIEL DE OLIVEIRA,MARCOS BEDO,None,None,None,FEDERAL INSTITUTE OF NORTH OF MINAS GERAIS,FEDERAL INSTITUTE OF NORTH OF MINAS GERAIS,FLUMINENSE FEDERAL UNIVERSITY,FLUMINENSE FEDERAL UNIVERSITY,FLUMINENSE NORTHWEST INSTITUTE FLUMINENSE FEDERAL UNIVERSITY,None,None,None,METRIC SPACES,DIVERSIFIED SIMILARITY SEARCHING,RESULT DIVERSIFICATION,SIMILARITY SEARCHING,None
127,1990,J-EDA: A workbench for tuning similarity and diversity search parameters in content-based image retrieval,Data Desconhecida,Vol. 12 No. 2 (2021),"Content-based image retrieval, Result diversification, Similarity searching",JOÃO V. O. NOVAES,LÚCIO F. D. SANTOS,LUIZ OLMES CARVALHO,DANIEL DE OLIVEIRA,MARCOS V. N. BEDO,AGMA J. M. TRAINA,CAETANO TRAINA JR.,None,UNIVERSITY OF SÃO PAULO (ICMC/USP),FEDERAL INSTITUTE OF TECHNOLOGY OF NORTH OF MINAS GERAIS (IFNMG),FEDERAL UNIVERSITY OF ITAJUBÁ (UNIFEI),FLUMINENSE FEDERAL UNIVERSITY (IC/UFF),FLUMINENSE FEDERAL UNIVERSITY (INFES/UFF),UNIVERSITY OF SÃO PAULO (ICMC/USP),UNIVERSITY OF SÃO PAULO (ICMC/USP),None,CONTENT-BASED IMAGE RETRIEVAL,RESULT DIVERSIFICATION,SIMILARITY SEARCHING,None,None
128,1988,Managing Hypothesis of Scientific Experiments with PhenoManager,Data Desconhecida,Vol. 12 No. 2 (2021),"Scientific experiment, Phenomena, Hypothesis, Scientific workflows, Project management",LEONARDO RAMOS,FABIO PORTO,DANIEL DE OLIVEIRA,None,None,None,None,None,UNIVERSIDADE FEDERAL FLUMINENSE,NATIONAL LABORATORY OF SCIENTIFIC COMPUTING (LNCC),UNIVERSIDADE FEDERAL FLUMINENSE,None,None,None,None,None,SCIENTIFIC EXPERIMENT,PHENOMENA,HYPOTHESIS,SCIENTIFIC WORKFLOWS,PROJECT MANAGEMENT
140,2017,Polyflow: a Polystore-compliant Mechanism to Provide Interoperability to Heterogeneous Provenance Graphs,Data Desconhecida,Vol. 11 No. 3 (2020),"Polystore, Syntactic interoperability, Semantic interoperability",YAN MENDES,DANIEL DE OLIVEIRA,VICTOR STRÖELE,None,None,None,None,None,FEDERAL UNIVERSITY OF JUIZ DE FORA,FLUMINENSE FEDERAL UNIVERSITY,FEDERAL UNIVERSITY OF JUIZ DE FORA,None,None,None,None,None,POLYSTORE,SYNTACTIC INTEROPERABILITY,SEMANTIC INTEROPERABILITY,None,None
182,1635,Beyond hit-or-miss: a comparative study of synopses for similarity searching,Data Desconhecida,Vol. 9 No. 1 (2018),"Similarity searching, Cost model, Synopsis, Distance distribution",MARCOS V. N. BEDO,DANIEL DE OLIVEIRA,AGMA J. M. TRAINA,CAETANO TRAINA JR.,None,None,None,None,FLUMINENSE FEDERAL UNIVERSITY,FLUMINENSE FEDERAL UNIVERSITY,UNIVERSITY OF SÃO PAULO,UNIVERSITY OF SÃO PAULO,None,None,None,None,SIMILARITY SEARCHING,COST MODEL,SYNOPSIS,DISTANCE DISTRIBUTION,None
185,1638,Towards an Empirical Evaluation of Scientific Data Indexing and Querying,Data Desconhecida,Vol. 9 No. 1 (2018),"Computational fluid dynamics, Dataflow management, Scientific data indexing, Scientific data querying",THAYLON GUEDES,VÍTOR SILVA,JOSÉ CAMATA,MARCOS V. N. BEDO,MARTA MATTOSO,DANIEL DE OLIVEIRA,None,None,UNIVERSIDADE FEDERAL FLUMINENSE,UNIVERSIDADE FEDERAL DO RIO DE JANEIRO,UNIVERSIDADE FEDERAL DE JUIZ DE FORA,UNIVERSIDADE FEDERAL FLUMINENSE,UNIVERSIDADE FEDERAL DO RIO DE JANEIRO,UNIVERSIDADE FEDERAL FLUMINENSE,None,None,COMPUTATIONAL FLUID DYNAMICS,DATAFLOW MANAGEMENT,SCIENTIFIC DATA INDEXING,SCIENTIFIC DATA QUERYING,None
198,1615,Spatiotemporal Anomaly Detection Applied to Flow Measurement Points in Natural Gas Production Plants,Data Desconhecida,Vol. 8 No. 2 (2017),"Anomaly detection, Dynamic bayes net, Flow measurement points",HADRIEL TOLEDO LIMA,FLAVIA BERNARDINI,None,None,None,None,None,None,UNIVERSIDADE FEDERAL FLUMINENSE,UNIVERSIDADE FEDERAL FLUMINENSE,None,None,None,None,None,None,ANOMALY DETECTION,DYNAMIC BAYES NET,FLOW MEASUREMENT POINTS,None,None
199,1603,Querying Provenance along with External Domain Data Using Prolog,Data Desconhecida,Vol. 8 No. 1 (2017),"Provenance analysis, Scientific experiments, Workflows",WELLINGTON OLIVEIRA,KARY A. C. S. OCAÑA,DANIEL DE OLIVEIRA,VANESSA BRAGANHOLO,None,None,None,None,UNIVERSIDADE FEDERAL FLUMINENSE\n\nINSTITUTO FEDERAL DO SUDESTE DE MINAS GERAIS - RIO POMBA CAMPUS,LABORATÓRIO NACIONAL DE COMPUTAÇÃO CIENTÍFICA,UNIVERSIDADE FEDERAL FLUMINENSE,UNIVERSIDADE FEDERAL FLUMINENSE,None,None,None,None,PROVENANCE ANALYSIS,SCIENTIFIC EXPERIMENTS,WORKFLOWS,None,None
215,1585,A Fast and Effective Strategy for Feature Selection in High-dimensional Datasets,Data Desconhecida,Vol. 7 No. 2 (2016),"Classification, Feature selection, High-dimensional datasets",MARIANA TASCA,ALEXANDRE PLASTINO,CELSO RIBEIRO,BIANCA ZADROZNY,None,None,None,None,UNIVERSIDADE FEDERAL FLUMINENSE,UNIVERSIDADE FEDERAL FLUMINENSE,UNIVERSIDADE FEDERAL FLUMINENSE,IBM RESEARCH,None,None,None,None,CLASSIFICATION,FEATURE SELECTION,HIGH-DIMENSIONAL DATASETS,None,None
232,1555,Information Gain Feature Selection for Multi-Label Classification,Data Desconhecida,Vol. 6 No. 1 (2015),"Classification, Data mining, Feature selection, Multi-label classification",RAFAEL B. PEREIRA,ALEXANDRE PLASTINO,BIANCA ZADROZNY,LUIZ H. C. MERSCHMANN,None,None,None,None,UNIVERSIDADE FEDERAL FLUMINENSE (UFF),UNIVERSIDADE FEDERAL FLUMINENSE,IBM RESEARCH,UNIVERSIDADE FEDERAL DE OURO PRETO (UFOP),None,None,None,None,CLASSIFICATION,DATA MINING,FEATURE SELECTION,MULTI-LABEL CLASSIFICATION,None
317,1461,Improving Local Per Level Hierarchical Classification,Data Desconhecida,Vol. 3 No. 3 (2012),"Classification, Data mining, Hierarchical classification",BRUNO C. PAES,ALEXANDRE PLASTINO,ALEX A. FREITAS,None,None,None,None,None,UNIVERSIDADE FEDERAL FLUMINENSE,UNIVERSIDADE FEDERAL FLUMINENSE,UNIVERSITY OF KENT,None,None,None,None,None,CLASSIFICATION,DATA MINING,HIERARCHICAL CLASSIFICATION,None,None
342,1420,Improving Lazy Attribute Selection,Data Desconhecida,Vol. 2 No. 3 (2011),"Attribute selection, Classification, Lazy learning",RAFAEL B. PEREIRA,ALEXANDRE PLASTINO,BIANCA ZADROZNY,LUIZ H. DE C. MERSCHMANN,ALEX A. FREITAS,None,None,None,UNIVERSIDADE FEDERAL FLUMINENSE,UNIVERSIDADE FEDERAL FLUMINENSE,IBM RESEARCH,UNIVERSIDADE FEDERAL DE OURO PRETO,UNIVERSITY OF KENT,None,None,None,ATTRIBUTE SELECTION,CLASSIFICATION,LAZY LEARNING,None,None
377,1283,HiSP-GC: A Classification Method Based on Probabilistic Analysis of Patterns,Data Desconhecida,Vol. 1 No. 3 (2010),Classifi,LUIZ MERSCHMANN,ALEXANDRE PLASTINO,None,None,None,None,None,None,FEDERAL UNIVERSITY OF OURO PRETO,FLUMINENSE FEDERAL UNIVERSITY,None,None,None,None,None,None,CLASSIFI,None,None,None,None

Alunos Por instituicao ( Em cada faculdade quantas pessoas tem )

In [72]:
cols = [f'instituicao_{i}' for i in range(1, 9)]

df_long = df[cols].melt(value_name='instituicao').dropna()

resultado = df_long['instituicao'].value_counts().reset_index()
resultado.columns = ['instituicao', 'count']

resultado = resultado.sort_values('count', ascending=False)

resultado

,instituicao,count
0,UNIVERSIDADE FEDERAL DE MINAS GERAIS,188
1,UNIVERSITY OF SÃO PAULO,84
2,UNIVERSIDADE FEDERAL DO CEARÁ,51
3,UNIVERSIDADE DE SÃO PAULO,46
4,UNIVERSIDADE FEDERAL FLUMINENSE,45
5,UFMG,35
6,UNIVERSIDADE FEDERAL DE GOIÁS,28
7,UNIVERSIDADE FEDERAL DO AMAZONAS,27
8,PUC-RIO,26
9,UNIVERSIDADE FEDERAL DO RIO GRANDE DO SUL,22
10,UNIVERSIDADE FEDERAL DE CAMPINA GRANDE,21
11,UNIVERSIDADE FEDERAL DE PERNAMBUCO,18
12,UNIVERSIDADE FEDERAL DO PARANÁ,18
13,FEDERAL UNIVERSITY OF PERNAMBUCO,18
14,FEDERAL UNIVERSITY OF CEARÁ,17
15,FLUMINENSE FEDERAL UNIVERSITY,16
16,UNIVERSIDADE FEDERAL DE SANTA CATARINA,15
17,FEDERAL UNIVERSITY OF CAMPINA GRANDE,15
18,UNIVERSIDADE FEDERAL DE UBERLÂNDIA,15
19,COPPE/UFRJ,14
20,UFRJ,14
21,FEDERAL UNIVERSITY OF SÃO CARLOS,12
22,PONTIFICAL CATHOLIC UNIVERSITY OF MINAS GERAIS,12
23,UNIVERSIDADE FEDERAL DO RIO DE JANEIRO,11
24,UFRGS,11
25,FEDERAL UNIVERSITY OF UBERLÂNDIA,11
26,ICMC-USP,11
27,UNIVERSITY OF CAMPINAS,10
28,UNIVERSIDADE FEDERAL DE OURO PRETO,10
29,UNIVERSIDADE FEDERAL DO RIO GRANDE,9
30,UNIVERSITY OF IA,9
31,FEDERAL CENTER OF TECHNOLOGICAL EDUCATION OF RIO DE JANEIRO,9
32,PONTIFÍCIA UNIVERSIDADE CATÓLICA DO RIO GRANDE DO SUL,9
33,UNIVERSIDADE FEDERAL DE SÃO CARLOS,9
34,ICMC - USP,9
35,UFF,9
36,FEDERAL UNIVERSITY OF PARANÁ,8
37,UNIVERSIDADE FEDERAL DO ESPÍRITO SANTO,8
38,UNIVERSIDADE FEDERAL DE SÃO JOÃO DEL REI,8
39,UNICAMP,8
40,INSTITUTE OF COMPUTING UNICAMP,8
41,ICMC-USP SAO CARLOS,8
42,UNIVERSIDADE DE FORTALEZA,7
43,FUNDAÇÃO OSWALDO CRUZ,7
44,HOSPITAL DE CLÍNICAS DE PORTO ALEGRE,7
45,UNIVERSIDADE DE BRASÍLIA,7
46,PONTIFÍCIA UNIVERSIDADE CATÓLICA DO RIO DE JANEIRO (PUC-RIO),7
47,FEDERAL UNIVERSITY OF FRONTEIRA SUL,7
48,FEDERAL UNIVERSITY OF RIO DE JANEIRO,7
49,FEDERAL UNIVERSITY OF MINAS GERAIS,7
50,INPE - NATIONAL INSTITUTE FOR SPACE RESEARCH,7
51,FEDERAL UNIVERSITY OF PARAÍBA,7
52,UFC,7
53,PEB/COPPE-FEDERAL UNIVERSITY OF RIO DE JANEIRO,6
54,UNIVERSIDADE FEDERAL RURAL DE PERNAMBUCO,6
55,COPPE/FEDERAL UNIVERSITY OF RIO DE JANEIRO,6
56,FEDERAL UNIVERSITY OF JUIZ DE FORA,6
57,UNIVERSIDADE DE PERNAMBUCO,6
58,UNIVERSIDADE FEDERAL DO RIO GRANDE DO SUL (UFRGS),6
59,UNIVERSITY OF SÃO PAULO USP,6
60,FEDERAL UNIVERSITY OF ESPÍRITO SANTO,6
61,UFSC,6
62,UNIVERSITY OF LUXEMBOURG,6
63,UNIRIO,6
64,UNIVERSITY OF ALBERTA,6
65,FEDERAL UNIVERSITY OF CEARÁ (UFC),6
66,UNIVERSITY OF FEIRA DE SANTANA,5
67,SANTA CATARINA STATE UNIVERSITY,5
68,FEDERAL UNIVERSITY OF RIO GRANDE DO SUL,5
69,UNIVERSIDADE FEDERAL DE ALAGOAS,5
70,INSTITUTO NACIONAL DE PESQUISAS ESPACIAIS,5
71,UNIVERSIDADE TECNOLÓGICA FEDERAL DO PARANÁ,5
72,LABORATÓRIO DE SISTEMAS DE INFORMAÇÃO UNIVERSIDADE FEDERAL DE CAMPINA GRANDE (UFCG) -,5
73,COMPUTER SCIENCE DEPARTMENT UNIVERSIDADE FEDERAL DE MINAS GERAIS,5
74,UNIVERSITY OF SAO PAULO (USP) AT SAO CARLOS,5
75,DATABASES AND DISTRIBUTED SYSTEMS GROUP TECHNISCHE UNIVERSITÄT DARMSTADT,5
76,UFAM,5
77,FEDERAL UNIVERSITY OF PARANÁ (UFPR),4
78,UNIVERSIDADE FEDERAL DE VIÇOSA,4
79,UNIVERSIDADE ESTADUAL DE CAMPINAS,4
80,UNIVERSIDADE FEDERAL RURAL DO SEMI-ÁRIDO,4
81,UNIVERSIDADE PAULISTA,4
82,NATIONAL LABORATORY FOR SCIENTIFIC COMPUTING,4
83,FEDERAL UNIVERSITY OF SÃO JOÃO DEL-REI,4
84,FEDERAL UNIVERSITY OF OURO PRETO,4
85,UNIVERSITY OF STUTTGART,4
86,GOGEO,4
87,DEPARTAMENTO DE INFORMÁTICA - UNIVERSIDADE FEDERAL DE VIÇOSA,4
88,PONTIFÍCIA UNIVERSIDADE CATÓLICA DE MINAS GERAIS - PUC MINAS,4
89,UNIVERSIDADE FEDERAL FLUMINESE,4
90,UNIVERSITY OF FORTALEZA - UNIFOR,4
91,ICMC - UNIVERSITY OF SÃO PAULO AT SÃO CARLOS -,4
92,CARNEGIE MELLON UNIVERSITY,4
93,UFSCAR,4
94,IBM RESEARCH,4
95,UNIVERSITY OF UTAH,4
96,ESCOLA POLITÉCNICA DA UNIVERSIDADE DE SÃO PAULO,3
97,INSTITUTO FEDERAL DE MINAS GERAIS,3
98,PROGRAMA DE PÓS-GRADUAÇÃO EM SENSORIAMENTO REMOTO (PGSER) COORDENAÇÃO DE ENSINO PESQUISA E EXTENSÃO (COEPE) INSTITUTO NACIONAL DE PESQUISAS ESPACIAIS (INPE),3
99,UNIVERSIDADE ESTADUAL DE MARINGÁ,3
100,INSTITUTE OF COMPUTING - UFF,3
101,CENTRO FEDERAL DE EDUCAÇÃO TECNOLÓGICA DE MINAS GERAIS,3
102,UNIVERSITY OF BRASÍLIA,3
103,FEDERAL UNIVERSITY OF TECHNOLOGY - PARANÁ,3
104,FEDERAL UNIVERSITY OF PIAUÍ,3
105,UNIVERSITY OF SÃO PAULO (ICMC/USP),3
106,UNIVERSIDADE FEDERAL DE SANTA CATARINA (UFSC),3
107,FEDERAL UNIVERSITY OF PARA,3
108,PONTIFICAL CATHOLIC UNIVERSITY OF RIO DE JANEIRO,3
109,UNIVERSITY OF BRASÍLIA (UNB),3
110,FEDERAL UNIVERSITY OF BAHIA,3
111,FEDERAL UNIVERSITY OF CAMPINA GRANDE - UFCG,3
112,INSTITUTE OF COMPUTING -- UNICAMP,3
113,INSTITUTO DE INFORMÁTICA UNIVERSIDADE FEDERAL DE GOIÁS,3
114,CIN-UFPE,3
115,CENIDET,3
116,IFPB,3
117,UNIFOR,3
118,INSTITUTE OF MATHEMATICS AND STATISTICS UNIVERSITY OF SÃO PAULO,3
119,FEDERAL UNIVERSITY OF AMAZONAS,3
120,INSTITUTE OF PARALLEL AND DISTRIBUTED SYSTEMS UNIVERSITY OF STUTTGART,3
121,UEL,3
122,UFC - UNIVERSIDADE FEDERAL DO CEARA,3
123,UNIVERSIDAD NACIONAL DE ROSARIO,3
124,ICMC - USP AT SÃO CARLOS,3
125,SAP GERMANY,3
126,LABORATÓRIO NACIONAL DE COMPUTAÇÃO CIENTÍFICA,3
127,UNIVERSIDADE FEDERAL DE CAMINA GRANDE,3
128,UNIVERSITY OF CHILE,3
129,ICMC/USP,3
130,UFV,3
131,PONTIFÍCIA UNIVERSIDADE CATÓLICA DO RIO DE JANEIRO,3
132,SENAI INNOVATION INSTITUTE FOR MINERAL TECHNOLOGIES,3
133,UNIVERSITY OF KENT,3
134,FEDERAL INSTITUTE OF SÃO PAULO,3
135,UNIVERSIDADE FEDERAL DO AGRESTE DE PERNAMBUCO,2
136,UNIVERSIDADE FEDERAL DE SANTA CATARINA (UFSC) INSTITUTO FEDERAL SUL-RIO-GRANDENSE (IFSUL),2
137,INSTITUTO DE CIÊNCIAS MATEMÁTICAS E DE COMPUTAÇÃO (USP),2
138,UNIVERSIDADE FEDERAL DO PARÁ (UFPA),2
139,UNIVERSITY OF SÃO PAULO - SÃO CARLOS,2
140,UNIVERSIDADE FEDERAL DE MINAS GERAIS / UNIVERSIDADE FEDERAL DO OESTE DA BAHIA,2
141,FEDERAL UNIVESITY OF CEARÁ,2
142,FEDERAL INSTITUTE OF NORTH OF MINAS GERAIS,2
143,UNIVERSIDADE DE BRASÍLIA (UNB),2
144,UERJ,2
145,UNIVERSITY OF SAO PAULO,2
146,INSTITUTO FEDERAL DE SÃO PAULO,2
147,UNIVERSIDADE FEDERAL DO RIO DE JANEIRO (UFRJ),2
148,FEDERAL UNIVERSITY OF OURO PRETO (UFOP),2
149,INSTITUTE OF INFORMATICS - UFRGS,2
150,UFRPE - UNIVERSIDADE FEDERAL DE PERNAMBUCO,2
151,PONTIFÍCIA UNIVERSIDADE CATÓLICA DE MINAS GERAIS,2
152,PONTIFICIA UNIVERSIDADE CATOLICA DO RIO DE JANEIRO (PUC-RIO),2
153,LONDRINA STATE UNIVERSITY,2
154,STATE UNIVERSITY OF FEIRA DE SANTANA,2
155,UNIVERSITY OF BELGRADE,2
156,UNIVERSIDADE FEDERAL DE CAMPINA GRANDE (UFCG),2
157,FEDERAL UNIVERSITY OF SANTA CATARINA,2
158,INSTITUTO FEDERAL DE EDUCAÇÃO CIÊNCIA E TECNOLOGIA DA PARAÍBA,2
159,ITA - INSTITUTO TECNOLÓGICO DE AERONÁUTICA,2
160,FEDERAL UNIVERSITY OF CEARA,2
161,BTU COTTBUS,2
162,INSTITUTE OF MATHEMATICS AND STATISTICS UNIVERSITY OF SAO PAULO,2
163,PPGI/UFRJ,2
164,ICMC UNIVERSITY OF SAO PAULO (USP),2
165,CMU,2
166,VICTORIA UNIVERSITY OF WELLINGTON,2
167,UC-RIVERSIDE,2
168,AT&T LABS - RESEARCH,2
169,UNIVERSITY OF KAISERSLAUTERN,2
170,INSTITUTO FEDERAL DO PARANÁ (IFPR),2
171,EMBRAPA TERRITORIAL,2
172,INSTITUTO MILITAR DE ENGENHARIA,2
173,DEPARTMENT OF COMPUTER SCIENCE FEDERAL UNIVERSITY OF SÃO CARLOS (UFSCAR),2
174,UNIVERSITY OF THESSALY,2
175,UNIVERSIDADE FEDERAL DE SÃO JOÃO DEL-REI,2
176,FEDERAL UNIVERSITY OF MATO GROSSO DO SUL,2
177,FEDERAL UNIVERSITY OF GOIAS,2
178,UNIVERSIDADE FEDERAL DE ITAJUBÁ,2
179,UNIVERSIDADE FEDERAL DO CEAR,2
180,UFCG,2
181,UNIVERSIDADE ESTADUAL DO CEARÁ,2
182,SCHOOL OF ARTS SCIENCE AND HUMANITIES UNIVERSITY OF SAO PAULO,2
183,CEFET/RJ,2
184,DEPARTMENT OF NEW MEDIA TECHNOLOGY MODUL UNIVERSITY VIENNA,2
185,CEPAGRI - UNICAMP,2
186,SOFTWARE COMPETENCE CENTER HAGENBERG,2
187,UNIVERSIDADE DO ESTADO DO RIO GRANDE DO NORTE,2
188,FEDERAL UNIVERSITY OF SANTA MARIA,2
189,INSTITUTO TECNOLÓGICO DE AERONÁUTICA,2
190,INSTITUTO FEDERAL DO RIO GRANDE DO SUL,2
191,CONTROLADORIA GERAL DA UNIÃO,2
192,UNIVERSITY PARIS-DAUPHINE,2
193,UFPE,2
194,CEPAGRI - UNIVERSITY OF CAMPINAS,2
195,PROS-UPV,2
196,UNIVERSIDAD DE CONCEPCION,2
197,MODUL UNIVERSITY VIENNA DEPARTMENT OF NEW MEDIA TECHNOLOGY,2
198,OSWALDO CRUZ INSTITUTE FIOCRUZ,2
199,INSTITUTO SUPERIOR TÉCNICO/INESC-ID,2
200,USP-ICMC,2
201,UNIVERSITÉ DE TOURS,2
202,INRIA AND LIRMM MONTPELLIER,2
203,UNIVERSITY OF FORTALEZA,2
204,PUC-RIO - PONTIFICIA UNIVERSIDADE CATOLICA DO RIO DE JANEIRO,2
205,UNIVERSITÉ DE BOURGOGNE,2
206,ETIS-CNRS-ENSEA-UNIVERSITÉ DE CERGY PONTOISE,2
207,HEWLETT PACKARD ENTERPRISE,2
208,PPGEN-FEDERAL UNIVERSITY OF RIO DE JANEIRO,2
209,VIRGINIA TECH,2
210,UNIVERSIDADE DE SÃO PAULO UNIVERSIDADE FEDERAL DE MINAS GERAIS,1
211,ÅBO AKADEMI,1
212,EMBRAPA TERRITORIAL/UNIVERSIDADE FEDERAL DE SÃO CARLOS,1
213,UNIVERSIDADE FEDERAL DE SANTA MARIA,1
214,INSTITUTO MILITAR DE ENGENHARIA | CENTRO DE ANÁLISES DE SISTEMAS NAVAIS,1
215,UNIVERSIDADE DE SÃO PAULO/NORTH CAROLINA STATE UNIVERSITY,1
216,DEZOO UNIVERSIDADE FEDERAL DE SÃO JOÃO DEL REI,1
217,UNIVERSIDADE FEDERAL DE SÃO PAULO,1
218,GOVERNO DO ESTADO DE MINAS GERAIS - SECRETARIA DE ESTADO DE JUSTIÇA E SEGURANÇA PÚBLICA,1
219,UNIVERSIDADE FEDERAL DE PERNAMBUCO AND INSTITUTO FEDERAL DA BAHIA - CAMPUS EUCLIDES DA CUNHA,1
220,IMPLANTA IT SOLUTIONS LTDA,1
221,DEPARTMENT OF COMPUTER ENGINEERING FACENS UNIVERSITY,1
222,UNIVERSIDADE FEDERAL FLUMINENSE / UNIVERSIDADE FEDERAL DO AMAZONAS,1
223,UNIVERSIDADE DO ESTADO DO AMAZONAS,1
224,FEDERAL UNIVERSITY OF UBERLÂNDIA / GETULIO VARGAS FOUNDATION,1
225,UNIVERSIDADE FEDERAL DO RIO DE JANEIRO / FUNDAÇÃO OSWALDO CRUZ,1
226,INSTITUTO FEDERAL CATARINENSE - UNIVERSIDADE FEDERAL DE SANTA CATARINA,1
227,UNIVERSIDAD CATÓLICA SAN PABLO,1
228,FEDERAL UNIVERSITY OF ABC,1
229,INSTITUTO FEDERAL DO NORTE DE MINAS GERAIS (IFNMG),1
230,FEDERAL UNIVERSITY OF THE STATE OF RIO DE JANEIRO,1
231,UNIVERSIDADE FEDERAL DE MINAS GERAIS / CONTROLADORIA GERAL DA UNIÃO,1
232,FEDERAL UNIVERSITY OF TECHNOLOGY - FEDERAL UNIVERSITY OF PARANÁ,1
233,UNIVERSIDADE DE UBERLÂNDIA,1
234,UNIVERSIDADE FEDERAL FLUMINENSE\n\nINSTITUTO FEDERAL DO SUDESTE DE MINAS GERAIS - RIO POMBA CAMPUS,1
235,UNIVERSIDADE SALVADOR - UNIFACS LAUREATE\n\nHEIDELBERG UNIVERSITY,1
236,PETRÓLEO EIRO S.A,1
237,INSTITUTO FEDERAL DE EDUCAÇÃO CIÊNCIA E TECNOLOGIA TRIÂNGULO MINEIRO,1
238,USP-ICMC AND UFMS,1
239,UNIVERSIDADE FEDERAL DE CAMPINA GRANDE\n\nUNIVERSIDADE ESTADUAL DA PARAÍBA,1
240,UNIVERSIDADE FEDERAL FLUMINENSE (UFF),1
241,IAN ARMY TECHNOLOGICAL CENTER (CTEX),1
242,IFSP E UFSCAR,1
243,UNIVERSITY OF SÃO PAULO (USP),1
244,LUIZ CARLOS GOMES MOREIRA AND ROSANE MANZONI MOREIRA,1
245,UNIVERSITY OF LONDRINA,1
246,UNIVERSIDADE CATOLICA SAN PABLO,1
247,PONTIFICA UNIVERSIDAD CATOLICA DE CHILE,1
248,INSTITUTO ATLÂNTICO,1
249,VIENNA UNIVERSITY OF ECONOMICS AND BUSINESS INSTITUTE FOR INFORMATION BUSINESS,1
250,IBM -,1
251,AMARO JOSÉ DA SILVA,1
252,UNIVERSIDADE FEDERAL RURAL DA AMAZÔNIA,1
253,JUS,1
254,COLLEGE OF ENGINEERING TRIVANDRUM,1
255,GOIANO FEDERAL INSTITUTE OF EDUCATION SCIENCE AND TECHNOLOGY,1
256,ISBAN - GRUPO SANTANDER,1
257,UFV PRODABEL,1
258,CPQD FOUNDATION,1
259,INSTITUTO DE COMPUTACIÓN FACULTAD DE INGENIERÍA UNIVERSIDAD DE LA REPÚBLICA,1
260,DEPARTMENT OF INFORMATION SYSTEMS AND OPERATIONS VIENNA UNIVERSITY OF ECONOMICS AND BUSINESS,1
261,UFRJ AND BNDES,1
262,UFRGS AND IFRS,1
263,CEFET MG,1
264,UNIVERSITY OF MICHIGAN (UOFM) SCHOOL FOR ENVIRONMENT AND SUSTAINABILITY,1
265,UNIVERSIDADE FEDERAL DE VIÇOSA MANNA TEAM,1
266,FEIRA DE SANTANA HIGHER EDUCATION UNIT,1
267,UNIVERSITÉ PARIS CITÉ/UNIVERSIDADE DE SÃO PAULO,1
268,BARRETOS CANCER HOSPITAL AND OSWALDO CRUZ FOUNDATION,1
269,PROGRAMA DE PÓS GRADUAÇÃO EM BIOTECNOLOGIA UNIVERSIDADE FEDERAL DE SÃO JOÃO DEL REI,1
270,FEDERAL UNIVERSITY OF TECHNOLOGY – PARANÁ (UTFPR),1
271,TSUKUBA UNIVERSITY JAPAN,1
272,UNIFESP AND INSTITUTO TECNOLÓGICO DE AERONÁUTICA,1
273,LAW SCHOOL - UFF,1
274,CESAR SCHOOL,1
275,UNIVERSIDADE FEDERAL DO AMAZONAS / JUS,1
276,STATE UNIVERSITY OF MINAS GERAIS - FRUTAL / UNIVERSITY OF SÃO PAULO - SÃO CARLOS,1
277,UNIVERSIDADE FEDERAL DE MINAS GERAIS / INSTITUTO FEDERAL DE MINAS GERAIS,1
278,UNIVERSIDADE FEDERAL DA PARAÍBA,1
279,FEDERAL FLUMINENSE UNIVERSITY,1
280,FEDERAL INSTITUTE OF PIAUÍ,1
281,ORACLE,1
282,UNIVERSITY OF SÃO PAULO - FEDERAL UNIVERSITY OF MINAS GERAIS,1
283,FUNDAÇÃO GETÚLIO VARGAS (FGV),1
284,FEDERAL INSTITUTE OF TECHNOLOGY OF NORTH OF MINAS GERAIS (IFNMG),1
285,NATIONAL LABORATORY OF SCIENTIFIC COMPUTING (LNCC),1
286,UNIVERSIDADE FEDERAL DO MATO GROSSO (UFMT),1
287,SÃO PAULO UNIVERSITY,1
288,FEDERAL UNIVERSIY OF CEARÁ,1
289,UNIVERSIDADE DE PERNAMBUCO INSTITUTO FEDERAL DE PERNAMBUCO,1
290,VIENNA UNIVERSITY OF ECONOMICS AND BUSINESS,1
291,FEDERAL CENTER FOR TECHNOLOGICAL EDUCATION OF MINAS GERAIS,1
292,UNIFESP,1
293,BRADESCO BANK S.A.,1
294,SCHOOL OF ENGINEERING OF MINAS GERAIS,1
295,SECRETARIA DA FAZENDA DO ESTADO DE SÃO PAULO,1
296,FEDERAL UNIVERSITY OF LAVRAS,1
297,UNIVERSIDADE SALVADOR - UNIFACS LAUREATE\n\nBAHIA STATE UNIVERSITY – UNEB,1
298,INSTITUTO FEDERAL DE SANTA CATARINA,1
299,UNIVERSIDADE FEDERAL DE LAVRAS,1
300,EMBRAPA AGRICULTURAL INFORMATICS,1
301,UFRRJ,1
302,UFU,1
303,UNIVERSIDAD DE SÃO PAULO,1
304,BIG DATA LAB - HITACHI AMERICA LTD - RD,1
305,UNIVERSITY OF BELGRADE\n\nINDIANA UNIVERSITY,1
306,MILITARY INSTITUTE OF ENGINEERING (IME),1
307,FEDERAL UNIVERSITY OF MATO GROSSO DO SUL (UFMS),1
308,EMBRAPA AGRICULTURAL INFORMATICS - CAMPINAS,1
309,INSTITUTO FEDERAL DE EDUCAÇÃO CIÊNCIA E TECNOLOGIA DE SÃO PAULO - CAMPUS SÃO CARLOS,1
310,UFOP - UNIVERSIDADE FEDERAL DE OURO PRETO,1
311,IC/UFF,1
312,UNIVERSITY OF APPLIED SCIENCES CHUR FACULTY OF INFORMATION SCIENCE,1
313,INDIAN INSTITUTE OF TECHNOLOGY MADRAS,1
314,FUCAPI,1
315,UFMG UFOP,1
316,DUETO TECNOLOGIA LTDA,1
317,CISI/COPPE/UFRJ,1
318,UNIVERSITY OF TORONTO,1
319,EMBRAPA AGRICULTURE INFORMATICS AT CAMPINAS -,1
320,UNIVERSIDADE FEDERAL DE SÃO CARLOS (UFSCAR),1
321,INSTITUTO FEDERAL DE EDUCAÇÃO CIÊNCIA E TECNOLOGIA DE SÃO PAULO,1
322,FEDERAL CENTER FOR TECHNOLOGICAL EDUCATION OF MINAS GERAIS (CEFET-MG),1
323,UFBA,1
324,INSTITUTO FEDERAL SUL-RIO-GRANDENSE (IFSUL),1
325,UNIVERSIDADE FEDERAL DA FRONTEIRA SUL (UFFS),1
326,CINNECTA - PART OF MATERA,1
327,INSTITUTO MAUÁ DE TECNOLOGIA,1
328,INSTITUTO MILITAR DE ENGENHARIA | MINISTÉRIO DA DEFESA,1
329,INSTITUTO FEDERAL DE EDUCAÇÃO CIÊNCIA E TECNOLOGIA DO PARANÁ,1
330,NORTH CAROLINA STATE UNIVERSITY,1
331,PROGRAMA DE PÓS GRADUAÇÃO EM BIOINFORMÁTICA UNIVERSIDADE FEDERAL DE MINAS GERAIS,1
332,FEDERAL UNIVERSITY OF PARANÁ / FEDERAL INSTITUTE OF PARANÁ,1
333,FEDERAL INSTITUTE OF EDUCATION SCIENCE AND TECHNOLOGY BAIANO,1
334,FEDERAL UNIVERSITY OF ITAJUBÁ (UNIFEI),1
335,MERCADO LIVRE,1
336,UNIVERSITY OF THE STATE OF RIO DE JANEIRO,1
337,UNIV. GRENOBLE ALPES CNRS,1
338,UNIVERSIDADE FEDERAL DE JUIZ DE FORA,1
339,JAMES COOK UNIVERSITY AND UNIVERSITY OF SÃO PAULO,1
340,UNIVERSIDADE FEDERAL DE PERNAMBUCO CENTRO DE INFORMÁTICA - CIN/UFPE.,1
341,INSTITUTE OF BIOLOGY -- UNICAMP,1
342,INSTITUTO AMBIENTAL E TECNOLÓGICO DA AMAZÔNIA,1
343,UNIVERSIDADE ESTADUAL DA PARAÍBA (UEPB),1
344,UNIVERSITÉ DE LYON CNRS INSA-LYON LIRIS FRANCE,1
345,DALHOUSIE UNIVERSITY,1
346,UNIVERSITY OF SÃO PAULO (USP),1
347,INRIA - UNIVERSITY OF NANTES,1
348,ISTI-CNR,1
349,NATIONAL INSTITUTE FOR SPACE RESEARCH (INPE),1
350,CENTER FOR EXPERIMENTAL RESEARCH IN COMPUTER SYSTEMS GEORGIA INSTITUTE OF TECHNOLOGY,1
351,UNIVERSITY OF OTTAWA,1
352,DATA DOMAIN,1
353,UFPE - UNIVERSIDADE FEDERAL DE PERNAMBUCO,1
354,FEDERAL RURAL UNIVERSITY OF PERNAMBUCO,1
355,INSTITUTE OF COMPUTING/UNIVERSITY OF CAMPINAS,1
356,UNIVERSIDAD NACIONAL DE SAN LUIS,1
357,CEPAGRI - STATE UNIVERSITY OF CAMPINAS -,1
358,FEDERAL UNIVERSITY OF TECHNOLOGY - PARANÁ (UTFPR),1
359,CONSIGLIO NAZIONALE DELLE RICERCHE (CNR) -ISTI,1
360,UNIVERSIDADE FEDERAL DE SÃO CARLOS,1
361,SÃO PAULO STATE UNIVERSITY (UNESP) SCHOOL OF SCIENCES AND ENGINEERING TUPÃ,1
362,UNIVERSITÈ PARIS-SACLAY CEA LIST,1
363,UNIVERSIDADE ESTADUAL PAULISTA JÚLIO DE MESQUITA FILHO,1
364,UNIVERSIDADE FEDERAL DO TRIÂNGULO MINEIRO/UNIVERSIDADE DE SÃO PAULO,1
365,DEPARTAMENTO DE CIÊNCIA DA COMPUTAÇÃO UNIVERSIDADE FEDERAL DE SÃO JOÃO DEL REI,1
366,FLUMINENSE FEDERAL UNIVERSITY / POLÍCIA MILITAR DO ESTADO DO RIO DE JANEIRO,1
367,JET PROPULSION LABORATORY-NASA,1
368,FLUMINENSE FEDERAL UNIVERSITY (IC/UFF),1
369,UNIVERSITY OF NEW SOUTH WALES,1
370,INRIA UNIVERSITY OF MONTPELLIER CNRS LIRMM FRANCE,1
371,UNIVERSITY OF LONDRINA UEL,1
372,SEEK AL LABS,1
373,UNIVERSIDADE FEDERAL RURAL DE PERNAMBUCO (UFRPE),1
374,UNIVERSIDADE FEDERAL DE OURO PRETO (UFOP),1
375,USP,1
376,ECSE - RENSSELAER POLYTECHNIC INSTITUTE,1
377,UNIVERSIDADE ESTADUAL DO NORTE DO PARANÁ,1
378,RENSSELAER POLYTECHNIC INSTITUTE,1
379,INSTITUTO DE COMPUTACAO UNICAMP,1
380,UNIVERSIDADE FEDERAL DE SÃO JOÃO DEL RE,1
381,METHODIST UNIVERSITY OF PIRACICABA,1
382,PRODABEL,1
383,UNIVERSIDADE ESTADUAL DE PONTA GROSSA,1
384,INSTITUIÇÃO NÃO INFORMADA,1
385,SANTA CATARINA AGRICULTURAL RESEARCH AND EXTENSION CORPORATION (EPAGRI),1
386,UNIVERSIDADE DE SÃO PAULO/UNIVERSITÉ PARIS CITÉ,1
387,ESCOLA EIRA DE ADMINISTRAÇÃO PÚBLICA E DE EMPRESAS FUNDAÇÃO GETULIO VARGAS (FGV),1
388,UNIVERSITY OF WESTERN ONTARIO,1
389,UNIVERSIDADE FEDERAL DO RIO DE JANEIRO / UNIVERSIDADE FEDERAL RURAL DO RIO DE JANEIRO,1
390,INRIA - UNIVERSITY OF MONTPELLIER,1
391,LUIZALABS,1
392,FLUMINENSE NORTHWEST INSTITUTE FLUMINENSE FEDERAL UNIVERSITY,1
393,FLUMINENSE FEDERAL UNIVERSITY (INFES/UFF),1
394,CHOCOLATE CLOUD,1
395,UNIVERSITY OF ALMERIA,1
396,DIGITRO TECNOLOGIA SA,1
397,UNIVERSITY OF LILLE E INRIA LILLE - NORD EUROPE,1
398,UNIVERSIDADE FEDERAL DO MARANHÃO,1
399,INRIA E LIRMM - UNIVERSITY OF MONTPELLIER,1
400,ZUNNIT TECHNOLOGIES,1
401,CENTER OF MATHEMATICS COMPUTING AND COGNITION FEDERAL UNIVERSITY OF ABC,1
402,SÃO PAULO FEDERAL INSTITUTE OF EDUCATION SCIENCE AND TECHNOLOGY,1
403,PPGCI/UFF,1
404,UNIVERSITAT POMPEU FABRA,1
405,FUNDAÇÃO OSWALDO CRUZ | INCA | PICTIS,1
406,UNIVESIDADE ESTADUAL DE CAMPINAS,1
407,UNIVERSIDADE AUTÓNOMA DE LISBOA,1
408,VALE INSTITUTE OF TECHNOLOGY,1
409,PONTIFICIA UNIVERSIDAD CATOLICA DE CHILE,1
410,FEDERAL INSTITUTE OF EDUCATION SCIENCE AND TECHNOLOGY OF PARAIBA,1
411,DEPT. OF COMPUTER SCIENCE UNIVERSIDAD DE CHILE,1
412,DIVISÃO DE OBSERVAÇÃO DA TERRA E GEOINFORMÁTICA (DIOTG) COORDENAÇÃO GERAL DE CIÊNCIAS DA TERRA (CG-CT),1

Alunos por Instituição (Pessoas Distintas)

In [73]:
df_autores_treated = autores.copy()
df_autores_treated = df_autores_treated.drop_duplicates()
df_autores_treated['inst'] = df_autores_treated['inst'].str.upper().apply(normalizar_instituicao)

In [74]:
df_autores_treated.groupby('inst').size().reset_index(name='count') \
    .sort_values('count', ascending=False)

,inst,count
164,UNIVERSIDADE FEDERAL DE MINAS GERAIS,197
147,UNIVERSIDADE DE SÃO PAULO,170
186,UNIVERSIDADE FEDERAL DO RIO DE JANEIRO,91
190,UNIVERSIDADE FEDERAL FLUMINENSE,61
180,UNIVERSIDADE FEDERAL DO CEARÁ,55
166,UNIVERSIDADE FEDERAL DE PERNAMBUCO,52
188,UNIVERSIDADE FEDERAL DO RIO GRANDE DO SUL,49
160,UNIVERSIDADE FEDERAL DE CAMPINA GRANDE,48
153,UNIVERSIDADE ESTADUAL DE CAMPINAS,43
178,UNIVERSIDADE FEDERAL DO AMAZONAS,29
167,UNIVERSIDADE FEDERAL DE SANTA CATARINA,28
89,INSTITUTO TECNOLÓGICO DE AERONÁUTICA,23
115,PUC-RIO,22
161,UNIVERSIDADE FEDERAL DE GOIÁS,22
145,UNIVERSIDADE DE BRASÍLIA,20
184,UNIVERSIDADE FEDERAL DO PARANÁ,19
165,UNIVERSIDADE FEDERAL DE OURO PRETO,18
43,FEDERAL UNIVERSITY OF CEARÁ,16
170,UNIVERSIDADE FEDERAL DE SÃO CARLOS,16
146,UNIVERSIDADE DE FORTALEZA,14
90,INSTITUTOS FEDERAIS,13
175,UNIVERSIDADE FEDERAL DE UBERLÂNDIA,11
67,FUNDAÇÃO OSWALDO CRUZ,10
134,UNIFESP,9
187,UNIVERSIDADE FEDERAL DO RIO GRANDE,9
51,FEDERAL UNIVERSITY OF PARANÁ,8
172,UNIVERSIDADE FEDERAL DE SÃO JOÃO DEL REI,8
181,UNIVERSIDADE FEDERAL DO ESPÍRITO SANTO,8
74,INPE - NATIONAL INSTITUTE FOR SPACE RESEARCH,7
53,FEDERAL UNIVERSITY OF PARAÍBA,7
60,FEDERAL UNIVERSITY OF UBERLÂNDIA,7
56,FEDERAL UNIVERSITY OF SÃO CARLOS,7
196,UNIVERSIDADE TECNOLÓGICA FEDERAL DO PARANÁ,7
45,FEDERAL UNIVERSITY OF FRONTEIRA SUL,6
44,FEDERAL UNIVERSITY OF ESPÍRITO SANTO,6
4,BRASIL,5
46,FEDERAL UNIVERSITY OF JUIZ DE FORA,5
21,"DATABASES AND DISTRIBUTED SYSTEMS GROUP, TECHNISCHE UNIVERSITÄT DARMSTADT",5
87,INSTITUTO NACIONAL DE PESQUISAS ESPACIAIS,5
159,UNIVERSIDADE FEDERAL DE ALAGOAS,5
103,NATIONAL LABORATORY FOR SCIENTIFIC COMPUTING,4
68,GOGEO,4
136,UNIRIO,4
214,UNIVERSITY OF STUTTGART,4
193,UNIVERSIDADE PAULISTA,4
192,UNIVERSIDADE FEDERAL RURAL DO SEMI-ÁRIDO,4
176,UNIVERSIDADE FEDERAL DE VIÇOSA,4
57,FEDERAL UNIVERSITY OF SÃO JOÃO DEL-REI,4
23,DEPARTAMENTO DE INFORMÁTICA - UNIVERSIDADE FEDERAL DE VIÇOSA,4
33,EMPRESA BRASILEIRA DE PESQUISA AGROPECUÁRIA,4
132,UFV,3
120,SENAI INNOVATION INSTITUTE FOR MINERAL TECHNOLOGIES,3
71,IBM RESEARCH,3
95,LABORATÓRIO NACIONAL DE COMPUTAÇÃO CIENTÍFICA,3
81,"INSTITUTE OF PARALLEL AND DISTRIBUTED SYSTEMS, UNIVERSITY OF STUTTGART",3
59,FEDERAL UNIVERSITY OF TECHNOLOGY - PARANÁ,3
42,FEDERAL UNIVERSITY OF BAHIA,3
40,FEDERAL INSTITUTE OF SÃO PAULO,3
50,FEDERAL UNIVERSITY OF PARA,3
54,FEDERAL UNIVERSITY OF PIAUÍ,3
32,EMORY UNIVERSITY,3
6,CARNEGIE MELLON UNIVERSITY,3
7,CENIDET,3
85,"INSTITUTO DE INFORMÁTICA, UNIVERSIDADE FEDERAL DE GOIÁS",3
35,ESCOLA POLITÉCNICA DA UNIVERSIDADE DE SÃO PAULO,3
202,UNIVERSITY OF BRASÍLIA,3
203,UNIVERSITY OF CHILE,3
210,UNIVERSITY OF LUXEMBOURG,3
197,UNIVERSITY OF ALBERTA,3
204,UNIVERSITY OF FEIRA DE SANTANA,3
141,UNIVERSIDAD NACIONAL DE ROSARIO,3
154,UNIVERSIDADE ESTADUAL DE MARINGÁ,3
48,FEDERAL UNIVERSITY OF MATO GROSSO DO SUL,2
101,"MODUL UNIVERSITY VIENNA, DEPARTMENT OF NEW MEDIA TECHNOLOGY",2
70,HEWLETT PACKARD ENTERPRISE,2
63,FEDERAL UNIVESITY OF CEARÁ,2
96,LONDRINA STATE UNIVERSITY,2
173,UNIVERSIDADE FEDERAL DE SÃO JOÃO DEL-REI,2
179,UNIVERSIDADE FEDERAL DO CEAR,2
185,UNIVERSIDADE FEDERAL DO PARÁ (UFPA),2
114,PROS-UPV,2
112,"PROGRAMA DE PÓS-GRADUAÇÃO EM SENSORIAMENTO REMOTO (PGSER), COORDENAÇÃO DE ENSINO, PESQUISA E EXTENSÃO (COEPE), INSTITUTO NACIONAL DE PESQUISAS ESPACIAIS (INPE)",2
117,SAP GERMANY,2
122,STATE UNIVERSITY OF FEIRA DE SANTANA,2
139,UNIVERSIDAD DE CONCEPCION,2
156,UNIVERSIDADE ESTADUAL DO CEARÁ,2
129,UERJ,2
128,UEL,2
217,UNIVERSITY OF UTAH,2
200,UNIVERSITY OF BELGRADE,2
215,UNIVERSITY OF THESSALY,2
219,UNIVERSITY PARIS-DAUPHINE,2
229,VIRGINIA TECH,2
14,CMU,2
55,FEDERAL UNIVERSITY OF SANTA MARIA,2
5,BTU COTTBUS,2
151,UNIVERSIDADE DO ESTADO DO RIO GRANDE DO NORTE,2
26,"DEPARTMENT OF NEW MEDIA TECHNOLOGY, MODUL UNIVERSITY VIENNA",2
10,CENTRO FEDERAL DE EDUCAÇÃO TECNOLÓGICA,2
17,CONTROLADORIA GERAL DA UNIÃO,2
1,ARQUIVO DO ESTADO DE SÃO PAULO,2
38,"FEDERAL INSTITUTE OF EDUCATION, SCIENCE AND TECHNOLOGY OF PARAIBA",1
39,FEDERAL INSTITUTE OF PIAUÍ,1
31,ECSE - RENSSELAER POLYTECHNIC INSTITUTE,1
102,NATIONAL INSTITUTE FOR SPACE RESEARCH (INPE),1
100,METHODIST UNIVERSITY OF PIRACICABA,1
98,LUIZALABS,1
99,MERCADO LIVRE,1
97,LUIZ CARLOS GOMES MOREIRA AND ROSANE MANZONI MOREIRA,1
92,ISTI-CNR,1
93,JET PROPULSION LABORATORY-NASA,1
94,JUSBRASIL,1
88,INSTITUTO SUPERIOR TÉCNICO/INESC-ID,1
91,ISBAN - GRUPO SANTANDER,1
77,"INRIA AND LIRMM, MONTPELLIER",1
80,INSTITUIÇÃO NÃO INFORMADA,1
83,INSTITUTO ATLÂNTICO,1
82,INSTITUTO AMBIENTAL E TECNOLÓGICO DA AMAZÔNIA,1
84,"INSTITUTO DE COMPUTACIÓN, FACULTAD DE INGENIERÍA, UNIVERSIDAD DE LA REPÚBLICA",1
86,INSTITUTO MAUÁ DE TECNOLOGIA,1
75,INRIA - UNIVERSITY OF MONTPELLIER,1
73,INDIAN INSTITUTE OF TECHNOLOGY MADRAS,1
72,IMPLANTA IT SOLUTIONS LTDA,1
76,INRIA - UNIVERSITY OF NANTES,1
78,INRIA E LIRMM - UNIVERSITY OF MONTPELLIER,1
79,"INRIA, UNIVERSITY OF MONTPELLIER, CNRS, LIRMM, FRANCE",1
41,FEDERAL UNIVERSITY OF ABC,1
47,FEDERAL UNIVERSITY OF LAVRAS,1
52,FEDERAL UNIVERSITY OF PARANÁ / FEDERAL INSTITUTE OF PARANÁ,1
62,FEDERAL UNIVERSIY OF CEARÁ,1
58,FEDERAL UNIVERSITY OF TECHNOLOGY - FEDERAL UNIVERSITY OF PARANÁ,1
61,FEDERAL UNIVERSITY OF UBERLÂNDIA / GETULIO VARGAS FOUNDATION,1
66,FUNDAÇÃO GETÚLIO VARGAS (FGV),1
65,FUCAPI,1
64,FEIRA DE SANTANA HIGHER EDUCATION UNIT,1
69,"GOIANO FEDERAL INSTITUTE OF EDUCATION, SCIENCE AND TECHNOLOGY",1
49,FEDERAL UNIVERSITY OF MATO GROSSO DO SUL (UFMS),1
20,DATA DOMAIN,1
18,CPQD FOUNDATION,1
19,DALHOUSIE UNIVERSITY,1
28,"DEZOO, UNIVERSIDADE FEDERAL DE SÃO JOÃO DEL REI",1
24,"DEPARTMENT OF COMPUTER ENGINEERING, FACENS UNIVERSITY",1
3,BRADESCO BANK S.A.,1
0,AMARO JOSÉ DA SILVA,1
2,AT&T LABS - RESEARCH,1
13,CINNECTA - PART OF MATERA,1
12,CHOCOLATE CLOUD,1
16,CONSIGLIO NAZIONALE DELLE RICERCHE (CNR) -ISTI,1
15,COLLEGE OF ENGINEERING TRIVANDRUM,1
11,CESAR SCHOOL,1
9,"CENTER OF MATHEMATICS, COMPUTING AND COGNITION, FEDERAL UNIVERSITY OF ABC",1
8,"CENTER FOR EXPERIMENTAL RESEARCH IN COMPUTER SYSTEMS, GEORGIA INSTITUTE OF TECHNOLOGY",1
22,"DEPARTAMENTO DE CIÊNCIA DA COMPUTAÇÃO, UNIVERSIDADE FEDERAL DE SÃO JOÃO DEL REI",1
30,DUETO TECNOLOGIA LTDA,1
29,DIGITRO TECNOLOGIA SA,1
34,ESCOLA BRASILEIRA DE ADMINISTRAÇÃO PÚBLICA E DE EMPRESAS FUNDAÇÃO GETULIO VARGAS (FGV),1
36,ETIS-CNRS-ENSEA-UNIVERSITÉ DE CERGY PONTOISE,1
37,"FEDERAL INSTITUTE OF EDUCATION, SCIENCE AND TECHNOLOGY BAIANO",1
25,"DEPARTMENT OF INFORMATION SYSTEMS AND OPERATIONS, VIENNA UNIVERSITY OF ECONOMICS AND BUSINESS",1
27,DEPT. OF COMPUTER SCIENCE UNIVERSIDAD DE CHILE,1
135,UNIFESP AND INSTITUTO TECNOLÓGICO DE AERONÁUTICA,1
133,"UFV, PRODABEL",1
130,UFBA,1
111,"PROGRAMA DE PÓS GRADUAÇÃO EM BIOTECNOLOGIA, UNIVERSIDADE FEDERAL DE SÃO JOÃO DEL REI",1
104,NATIONAL LABORATORY OF SCIENTIFIC COMPUTING (LNCC),1
105,NORTH CAROLINA STATE UNIVERSITY,1
106,ORACLE,1
110,PRODABEL,1
162,UNIVERSIDADE FEDERAL DE JUIZ DE FORA,1
163,UNIVERSIDADE FEDERAL DE LAVRAS,1
157,UNIVERSIDADE ESTADUAL DO NORTE DO PARANÁ,1
158,UNIVERSIDADE FEDERAL DA PARAÍBA,1
155,UNIVERSIDADE ESTADUAL DE PONTA GROSSA,1
152,UNIVERSIDADE ESTADUAL DA PARAÍBA (UEPB),1
149,UNIVERSIDADE DE SÃO PAULO/UNIVERSITÉ PARIS CITÉ,1
137,UNIV. GRENOBLE ALPES CNRS,1
143,UNIVERSIDADE AUTÓNOMA DE LISBOA,1
142,UNIVERSIDAD NACIONAL DE SAN LUIS,1
140,UNIVERSIDAD DE SÃO PAULO,1
138,UNIVERSIDAD CATÓLICA SAN PABLO,1
144,UNIVERSIDADE CATOLICA SAN PABLO,1
148,UNIVERSIDADE DE SÃO PAULO/NORTH CAROLINA STATE UNIVERSITY,1
150,UNIVERSIDADE DE UBERLÂNDIA,1
107,PETRÓLEO BRASILEIRO S.A,1
119,SEEK AL LABS,1
118,SECRETARIA DA FAZENDA DO ESTADO DE SÃO PAULO,1
116,RENSSELAER POLYTECHNIC INSTITUTE,1
113,"PROGRAMA DE PÓS-GRADUAÇÃO EM SENSORIAMENTO REMOTO (PGSER), COORDENAÇÃO DE ENSINO, PESQUISA E EXTENSÃO (COEPE), INSTITUTO NACIONAL DE PESQUISAS ESPACIAIS (INPE); DIVISÃO DE OBSERVAÇÃO DA TERRA E GEOINFORMÁTICA (DIOTG), COORDENAÇÃO GERAL DE CIÊNCIAS DA TERRA (CG-CT)",1
108,PONTIFICA UNIVERSIDAD CATOLICA DE CHILE,1
109,PONTIFICIA UNIVERSIDAD CATOLICA DE CHILE,1
121,SOFTWARE COMPETENCE CENTER HAGENBERG,1
123,"SÃO PAULO FEDERAL INSTITUTE OF EDUCATION, SCIENCE AND TECHNOLOGY",1
127,UC-RIVERSIDE,1
126,"TSUKUBA UNIVERSITY, JAPAN",1
125,SÃO PAULO UNIVERSITY,1
124,"SÃO PAULO STATE UNIVERSITY (UNESP), SCHOOL OF SCIENCES AND ENGINEERING, TUPÃ",1
131,UFRRJ,1
169,UNIVERSIDADE FEDERAL DE SÃO CARLOS,1
171,UNIVERSIDADE FEDERAL DE SÃO JOÃO DEL RE,1
177,"UNIVERSIDADE FEDERAL DE VIÇOSA, MANNA TEAM",1
199,"UNIVERSITY OF APPLIED SCIENCES CHUR, FACULTY OF INFORMATION SCIENCE",1
198,UNIVERSITY OF ALMERIA,1
194,UNIVERSIDADE SALVADOR - UNIFACS LAUREATE\n\nBAHIA STATE UNIVERSITY – UNEB,1
195,UNIVERSIDADE SALVADOR - UNIFACS LAUREATE\n\nHEIDELBERG UNIVERSITY,1
189,UNIVERSIDADE FEDERAL DO TRIÂNGULO MINEIRO/UNIVERSIDADE DE SÃO PAULO,1
191,UNIVERSIDADE FEDERAL RURAL DA AMAZÔNIA,1
182,UNIVERSIDADE FEDERAL DO MARANHÃO,1
183,UNIVERSIDADE FEDERAL DO MATO GROSSO (UFMT),1
174,UNIVERSIDADE FEDERAL DE SÃO PAULO,1
168,UNIVERSIDADE FEDERAL DE SANTA MARIA,1
207,UNIVERSITY OF LILLE E INRIA LILLE - NORD EUROPE,1
208,UNIVERSITY OF LONDRINA,1
211,"UNIVERSITY OF MICHIGAN (UOFM), SCHOOL FOR ENVIRONMENT AND SUSTAINABILITY",1
206,UNIVERSITY OF KENT,1
205,UNIVERSITY OF KAISERSLAUTERN,1
201,UNIVERSITY OF BELGRADE\n\nINDIANA UNIVERSITY,1
212,UNIVERSITY OF NEW SOUTH WALES,1
213,UNIVERSITY OF OTTAWA,1
209,"UNIVERSITY OF LONDRINA, UEL",1
216,UNIVERSITY OF TORONTO,1
220,"UNIVERSITÈ PARIS-SACLAY, CEA, LIST",1
221,UNIVERSITÉ DE BOURGOGNE,1
222,"UNIVERSITÉ DE LYON, CNRS, INSA-LYON, LIRIS, FRANCE",1
218,UNIVERSITY OF WESTERN ONTARIO,1
223,UNIVERSITÉ DE TOURS,1
224,UNIVERSITÉ PARIS CITÉ/UNIVERSIDADE DE SÃO PAULO,1
226,VICTORIA UNIVERSITY OF WELLINGTON,1
225,VALE INSTITUTE OF TECHNOLOGY,1
227,VIENNA UNIVERSITY OF ECONOMICS AND BUSINESS,1
228,"VIENNA UNIVERSITY OF ECONOMICS AND BUSINESS, INSTITUTE FOR INFORMATION BUSINESS",1
230,ZUNNIT TECHNOLOGIES,1
231,ÅBO AKADEMI,1

In [ ]:
!pip3 install openpyxl

import openpyxl

df.to_excel('teste.xlsx')

In [76]:
# import difflib

# # --- PARTE 1: Função de Mapeamento Fuzzy ---
# def criar_mapeamento_fuzzy(lista_nomes, threshold=0.4):
#     mapping = {}
#     processed = set()
#     # Ordenamos pelos nomes mais longos primeiro para servirem de padrão
#     lista_ordenada = sorted(list(lista_nomes), key=len, reverse=True)
    
#     for nome in lista_ordenada:
#         if nome in processed:
#             continue
#         # Busca nomes similares que ainda não foram "resolvidos"
#         similares = difflib.get_close_matches(nome, [n for n in lista_ordenada if n not in processed], n=10, cutoff=threshold)
#         for s in similares:
#             mapping[s] = nome
#             processed.add(s)
#     return mapping

# # --- PARTE 2: Aplicando no seu fluxo ---

# # 1. Definimos as colunas de autores
# cols_autores = [f'autor_{i}' for i in range(1, 9)]

# # 2. Extraímos todos os nomes únicos para criar o dicionário de tradução
# todos_nomes_sujos = pd.Series(df[cols_autores].values.ravel()).dropna().unique()
# mapeamento_limpo = criar_mapeamento_fuzzy(todos_nomes_sujos, threshold=0.8)

# # 3. Aplicamos a troca em todas as colunas de uma vez
# df[cols_autores] = df[cols_autores].replace(mapeamento_limpo)

# # 4. Agora geramos a sua lista final com os nomes já corrigidos
# nomes_pessoas_distintos = pd.Series(df[cols_autores].values.ravel()).dropna().unique()
# nomes_pessoas_lista = sorted(nomes_pessoas_distintos.tolist())

# # Exibir resultado
# print(f"Total de nomes antes do fuzzy: {len(todos_nomes_sujos)}")
# print(f"Total de nomes após o fuzzy: {len(nomes_pessoas_lista)}")
# print("\nLista de nomes padronizada:")
# for nome in nomes_pessoas_lista:
#     print(nome)

In [77]:
#Melhor ate o momento

import pandas as pd
import difflib
import re

def normalizar_para_comparacao(texto):
    # Remove pontos, acentos e espaços extras para facilitar a comparação
    texto = re.sub(r'\.', ' ', texto.upper())
    return " ".join(texto.split())

def sao_mesma_pessoa(nome1, nome2, threshold=0.8):
    # 1. Teste de similaridade padrão (para erros de digitação)
    ratio = difflib.SequenceMatcher(None, nome1, nome2).ratio()
    if ratio >= threshold:
        return True
    
    # 2. Teste de "Contenção" (para nomes abreviados ou curtos)
    # Ex: "AGMA TRAINA" dentro de "AGMA JUCI MACHADO TRAINA"
    n1 = normalizar_para_comparacao(nome1).split()
    n2 = normalizar_para_comparacao(nome2).split()
    
    # Identifica qual é o nome curto e qual é o longo
    curto, longo = (n1, n2) if len(n1) < len(n2) else (n2, n1)
    
    # Se o nome curto tem pelo menos 2 termos (Primeiro e Último nome)
    if len(curto) >= 2:
        # Verifica se o primeiro e o último nome batem exatamente
        if curto[0] == longo[0] and curto[-1] == longo[-1]:
            # Verifica se os outros termos do nome curto são iniciais ou partes do longo
            match_count = 0
            for termo in curto:
                if any(termo == parte or (len(termo) == 1 and parte.startswith(termo)) for parte in longo):
                    match_count += 1
            if match_count == len(curto):
                return True
                
    return False

def criar_mapeamento_fuzzy_avancado(lista_nomes):
    mapping = {}
    # Ordenamos do maior para o menor para que o nome completo seja o "pai"
    lista_ordenada = sorted(list(set(lista_nomes)), key=len, reverse=True)
    processed = set()

    for i in range(len(lista_ordenada)):
        nome_longo = lista_ordenada[i]
        if nome_longo in processed:
            continue
        
        for j in range(i + 1, len(lista_ordenada)):
            nome_curto = lista_ordenada[j]
            if nome_curto in processed:
                continue
            
            if sao_mesma_pessoa(nome_longo, nome_curto):
                mapping[nome_curto] = nome_longo
                processed.add(nome_curto)
        
        processed.add(nome_longo)
    return mapping

# --- APLICANDO NO SEU FLUXO ---

cols_autores = [f'autor_{i}' for i in range(1, 9)]
todos_nomes = pd.Series(df[cols_autores].values.ravel()).dropna().unique()

# Gera o mapeamento com a nova lógica
mapeamento_limpo = criar_mapeamento_fuzzy_avancado(todos_nomes)

# Aplica a substituição
df[cols_autores] = df[cols_autores].replace(mapeamento_limpo)

# Gera a lista final
nomes_pessoas_lista = sorted(pd.Series(df[cols_autores].values.ravel()).dropna().unique().tolist())

In [78]:
import pandas as pd
import re
import unicodedata
import difflib

def remover_acentos_e_limpar(texto):
    if not texto: return ""
    nfkd = unicodedata.normalize('NFD', str(texto).upper())
    texto_sem_acento = "".join([c for c in nfkd if unicodedata.category(c) != 'Mn'])
    return re.sub(r'[^A-Z\s]', ' ', texto_sem_acento)

def normalizar_para_comparacao(texto):
    limpo = remover_acentos_e_limpar(texto)
    return " ".join(limpo.split())

def sao_mesma_pessoa(nome1, nome2, threshold=0.85):
    n1_str = normalizar_para_comparacao(nome1)
    n2_str = normalizar_para_comparacao(nome2)
    
    if difflib.SequenceMatcher(None, n1_str, n2_str).ratio() >= threshold:
        return True
    
    t1, t2 = n1_str.split(), n2_str.split()
    curto, longo = (t1, t2) if len(t1) < len(t2) else (t2, t1)
    
    if len(curto) >= 2:
        if curto[0] == longo[0] and curto[-1] == longo[-1]:
            match_count = 0
            for termo in curto:
                if any(termo == parte or (len(termo) == 1 and parte.startswith(termo)) for parte in longo):
                    match_count += 1
            if match_count == len(curto):
                return True
    return False

def criar_mapeamento_fuzzy_total(lista_nomes):
    mapping = {}
    lista_ordenada = sorted(list(set(lista_nomes)), key=len, reverse=True)
    processed = set()

    for i in range(len(lista_ordenada)):
        nome_longo = lista_ordenada[i]
        if nome_longo in processed: continue
        
        for j in range(i + 1, len(lista_ordenada)):
            nome_curto = lista_ordenada[j]
            if nome_curto in processed: continue
            
            if sao_mesma_pessoa(nome_longo, nome_curto):
                mapping[nome_curto] = nome_longo
                processed.add(nome_curto)
        processed.add(nome_longo)
    return mapping

cols_autores = [f'autor_{i}' for i in range(1, 9)]

todos_nomes = pd.Series(df[cols_autores].values.ravel()).dropna().unique()

mapeamento_limpo = criar_mapeamento_fuzzy_total(todos_nomes)

df[cols_autores] = df[cols_autores].replace(mapeamento_limpo)

nomes_pessoas_lista = sorted(pd.Series(df[cols_autores].values.ravel()).dropna().unique().tolist())

print(f"Total de nomes originais: {len(todos_nomes)}")
print(f"Total de nomes unificados: {len(nomes_pessoas_lista)}")

Total de nomes originais: 1059
Total de nomes unificados: 1053

In [79]:

df_nomes_exportar = pd.DataFrame(nomes_pessoas_lista, columns=['nome_autor'])

df_nomes_exportar.to_csv('nomes_autores_distintos_pos_fuzy.csv', index=False, encoding='utf-8-sig')

print("Arquivo 'nomes_autores_distintos.csv' exportado com sucesso!")

Arquivo 'nomes_autores_distintos.csv' exportado com sucesso!

In [80]:

df_nomes = pd.DataFrame(nomes_pessoas_lista, columns=['Nome do Autor'])


df_nomes

                                        Nome do Autor
0                                   A. R. S. PARMEZAN
1                                       A. S. C. MELO
2                                      ABDUL NIZAR M.
3                              ABÍLIO NOGUEIRA BARROS
4                                  ADALBERTO CAJUEIRO
5                                      ADENILSO SIMAO
6                                    ADOLFO GUIMARÃES
7                                    ADRIANA MEXICANO
8                           ADRIANE FEIJÓ EVANGELISTA
9                           ADRIANO ARANTES PATERLINI
10                              ADRIANO C. M. PEREIRA
11                                    ADRIANO RIVOLLI
12                            ADRIANO VELASQUE WERHLI
13                                     ADRIANO VELOSO
14                          AFONSO MATHEUS SOUSA LIMA
15                           AGMA JUCI MACHADO TRAINA
16                                          ALAN LYRA
17                               ALBERT WEICHSELBRAUN
18                              ALBERTO H. F. LAENDER
19                                ALDO VON WANGENHEIM
20                                ALDRI L. DOS SANTOS
21                      ALDÉRYCK FÉLIX DE ALBUQUERQUE
22                                 ALEJANDRO BUCHMANN
23                            ALESSANDRO GUSTAVO FIOR
24                                    ALEX A. FREITAS
25                                     ALEXANDER OCSA
26                ALEXANDER YLNNER CHOQUENAIRA FLOREZ
27                               ALEXANDRE A. B. LIMA
28                               ALEXANDRE F. NOVELLO
29                             ALEXANDRE M. A. MACIEL
30                                 ALEXANDRE PLASTINO
31                        ALEXIS IVÁN ASPAUZA LESCANO
32                            ALFREDO GUILHERME SOUZA
33                                         ALINE PAES
34                                ALINE S. O. VALENTE
35                             ALLAN KARDEC S. SOARES
36                                        ALLAN SALES
37                            ALNEU  DE ANDRADE LOPES
38                           ALTIGRAN SOARES DA SILVA
39                              ALVARO R. PEREIRA JR.
40        ALVARO VALENTIM PEREIRA DE MENEZES BANDEIRA
41                             AMANDA D. P. VENCESLAU
42                                 AMON VEIGA SANTANA
43                                      ANA C. LORENA
44                                ANA C. Q. SIRAVENHA
45                                    ANA C. S. GOMES
46                              ANA CAROLINA M. PIRES
47                               ANA CAROLINA SALGADO
48               ANA CHRISTINA DE OLIVEIRA BRINGUENTE
49                       ANA CRISTINA FRANCO DA SILVA
50                           ANA EMÍLIA GOULART LEMOS
51                         ANA GABRIELLE RAMOS FALCÃO
52                                   ANA L. C. BAZZAN
53                                  ANA LUIZA SANCHES
54                           ANA LÚCIA MARREIROS MAIA
55                                 ANA MARIA H. ÁVILA
56                                    ANA PAULA APPEL
57                              ANA PAULA C. DA SILVA
58                              ANA PAULA DE CARVALHO
59                                 ANA PAULA REINALDO
60                               ANDERSON A. FERREIRA
61                           ANDERSON ALMEIDA FIRMINO
62                                  ANDERSON C. SILVA
63                            ANDERSON CHAVES CARNIEL
64                                  ANDERSON U. KAUER
65                                      ANDRE C. HORA
66                      ANDRE DALLA BERNARDINA GARCIA
67                       ANDRE LUIZ DA COSTA CARVALHO
68                                   ANDRE S. FURTADO
69                             ANDREA IABRUDI TAVARES
70                             ANDREI DE SOUZA INÁCIO
71                                  ANDREI L. QUEIROZ
72                         ANDRESSON DA SILVA FIRMINO
73                          ANDREZA FRANCISCO MARTINS
74                                   ANDRÉ A. BERTONI
75    ANDRÉ CARLOS PONCE DE LEON FERREIRA DE CARVALHO
76                              ANDRÉ FONSECA AMÂNCIO
77                               ANDRÉ L. C. MENDONÇA
78                                   ANDRÉ L. C. RÊGO
79                           ANDRÉ LUIZ FIRMINO ALVES
80                                     ANDRÉ MEDEIROS
81                             ANDRÉ MEDIOTE DE SOUSA
82                                   ANDRÉ NASCIMENTO
83                                    ANDRÉ SANTANCHÈ
84                                   ANDRÉA MAGALHÃES
85                           ANDRÊZA LEITE DE ALENCAR
86                              ANGELO AUGUSTO FROZZA
87                               ANGELO BATISTA NEVES
88                                     ANGELO BRAYNER
89                       ANGELO CESAR MENDES DA SILVA
90                           ANGÉLICA FÉLIX DE CASTRO
91                                     ANISIO LACERDA
92                          ANNATERCIA GOMES PINHEIRO
93                           ANSELMO CARDOSO DE PAIVA
94                             ANTONIO A. F. LOUREIRO
95                                     ANTONIO CORRAL
96                                 ANTONIO L. FURTADO
97                            ANTONIO LUIZ P. RIBEIRO
98                          ANTÔNIO JOSÉ C. RODRIGUES
99                                ANTÔNIO P. S. ALVES
100                          ANTÔNIO RICARDO K. CUNHA
101                               ARION DE CAMPOS JR.
102                                 ARISTÊNIO SARAIVA
103                                       ARLEI SILVA
104                            ARLINO H. M. DE ARAÚJO
105                                 ARNAUD GIACOMETTI
106                                       ARNO SCHARL
107                ARTHUR EMANUEL DE OLIVEIRA CAROSIA
108                                ARTHUR F. DA COSTA
109                         ARTHUR PROCHNOW BAUMGARDT
110                                     ARTUR ZIVIANI
111                                    ASTERIO TANAKA
112                                    ATSLANDS ROCHA
113                             AURELIO RIBEIRO COSTA
114                         BEATRIZ F. P. DE OLIVEIRA
115                          BERNADETTE FARIAS LÓSCIO
116                                BERNHARD MITSCHANG
117                             BERTHIER RIBEIRO-NETO
118                                   BIANCA ZADROZNY
119                         BRAULIO V. SÁNCHEZ VINCES
120                                  BRENO C. PIMENTA
121                                   BRENO CERQUEIRA
122                        BRUNA  HENRIQUE SACRAMENTO
123                                     BRUNA C. MELO
124                                BRUNO B. CIFARELLI
125                                     BRUNO C. PAES
126                                   BRUNO C. SANTOS
127                                    BRUNO CUNHA SÁ
128                                  BRUNO DE C. LEAL
129          BRUNO EDSON MARTINS DE ALBUQUERQUE FILHO
130                                     BRUNO ERBISTI
131                               BRUNO LORENÇO LOPES
132                                     BRUNO NOVELLI
133                                     BRUNO PADILHA
134                               BYRON L. D. BEZERRA
135                     BÁRBARA GABRIELLE C. O. LOPES
136                              BÁRBARA M. A. MENDES
137                                       C. D. SILVA
138                                       C. M. SOUZA
139                             CAETANO TRAINA JÚNIOR
140                                   CAIO B. NÓBREGA
141                              CAIO EDUARDO RIBEIRO
142                        CAIO LIBÂNIO MELO JERÔNIMO
143                                  CAIO MOURA DAOUD
144                                        CAIO PONTE
145                              CAIO VIKTOR S. AVILA
146                                CAIO ZAVA FERREIRA
147                                         CALTON PU
148                                    CAMILA FERRARI
149                                   CAMILA R. LOPES
150                                CARINA F. DORNELES
151                                     CARLA DELGADO
152                                   CARLA RODRIGUES
153                       CARLOS A. F. PIMENTEL FILHO
154                              CARLOS A. FELGUEIRAS
155                                  CARLOS A. HEUSER
156                                 CARLOS A. NORONHA
157                         CARLOS ABEL CÓRDOVA SÁENZ
158                            CARLOS ALESSANDRO SENA
159                             CARLOS ANDRES FERRERO
160                                    CARLOS CAMINHA
161                         CARLOS EDUARDO M. MOREIRA
162                            CARLOS EDUARDO PAULINO
163                           CARLOS EDUARDO S. PIRES
164                             CARLOS H. C. TEIXEIRA
165                           CARLOS HENRIQUE CÂNDIDO
166                           CARLOS JULIANO M. VIANA
167                           CARLOS MAGNO G. BARBOSA
168                              CARLOS S. S. MARINHO
169            CARLOS VINICIUS ALVES MINERVINO PONTES
170                              CARLYLE RIBEIRO LIMA
171                        CARMELO J. A. BASTOS-FILHO
172                                    CARMEM S. HARA
173                                  CAROLINA C. ROSA
174                             CAROLINA CORRÊA GIRON
175                                CAROLINA O. P. GIL
176                                CAROLINA R. XAVIER
177                               CATHERINE ETCHEBEST
178                                       CELIO TROIS
179                            CELSO A. SAIBEL SANTOS
180                                      CELSO FRANÇA
181                              CELSO MASSAKI HIRATA
182                                     CELSO RIBEIRO
183                               CHAULIO R. FERREIRA
184                                      CHIARA RENSO
185                                CHRISTIAN C. BONES
186                                  CHRISTIAN MATHIS
187                               CHRISTIAN MIDDLETON
188                                 CHRISTIAN SCHMITZ
189                                CHRISTOS FALOUTSOS
190                                    CLARA A. BACHA
191                                 CLARISSE SCOFIELD
192                           CLAUDIA BAUZER MEDEIROS
193                       CLAUDINEI GARCIA DE ANDRADE
194                            CLAUDIO D. G. LINHARES
195                                 CLAUDIO ESPERANÇA
196                                 CLAUDIO GUTIÉRREZ
197                          CLAUDIO M. V. DE ANDRADE
198                              CLAUDIVAN CRUZ LOPES
199                                CLAUS DE C. ARANHA
200                                     CLAYSON CELES
201                                  CLEBER DAMASCENO
202                                  CLEISON D. SILVA
203                                 CLODOVEU A. DAVIS
204                        CLODOVEU AUGUSTO DAVIS JR.
205                                 CLÁUDIA T. CODEÇO
206                         CLÁUDIO DE SOUZA BAPTISTA
207                             CLÁUDIO E. C. CAMPELO
208                       CLÁUDIO GUSTAVO S. CAPANEMA
209                                  CLÁUDIO VALIENSE
210                              CORA SILBERSCHNEIDER
211                                     CRISTIANE GEA
212                                CRISTIANE N. NOBRE
213                           CRISTIANO CORDEIRO CRUZ
214                             CRISTIANO L. N. PINTO
215                        CRISTIANO MARTINS MONTEIRO
216                                   CRISTINA BENDER
217                                CRISTINA D. AGUIAR
218                  CRISTINA DUTRA DE AGUIAR CIFERRI
219                          CRISTON PEREIRA DE SOUZA
220                                 CRÍCIA Z. FELÍCIO
221                 CYNTHIA DE OLIVEIRA LAGE FERREIRA
222                               CÉLIA GHEDINI RALHA
223                                        D. F. LIMA
224                                    D. L. CARVALHO
225                                    D. M. OLIVEIRA
226                                     DAMIRES SOUZA
227                                 DANIEL A. FURTADO
228                                     DANIEL BAUSCH
229                            DANIEL DA SILVA JUNIOR
230                                DANIEL DE OLIVEIRA
231                                 DANIEL FIGUEIREDO
232                                DANIEL HASAN DALIP
233                 DANIEL JEAN RODRIGUES VASCONCELOS
234                                 DANIEL L. JASBICK
235                                     DANIEL LUCANI
236                             DANIEL N. R. DA SILVA
237                               DANIEL S. GUIMARÃES
238                                  DANIEL S. KASTER
239                                    DANIEL SCHWABE
240                     DANIEL YOSHINOBU TAKADA CHINO
241                                     DANIELA PITTA
242                                    DANIELA VIANNA
243                              DANIELLE ALBUQUERQUE
244                             DANILO A. N. S. SILVA
245                              DANILO B. SEUFITELLI
246                               DANNY SUAREZ VARGAS
247                                DANUSA R. B. CUNHA
248                            DARLAN  TELES DA SILVA
249                                       DAVI ARNAUT
250                        DAVI ROMERO DE VASCONCELOS
251                                DAVID B. FERNANDES
252                               DAVID MENOTTI GOMES
253                          DEIVIDY AMORIM POLICARPO
254                             DEMETRIO GOMES MESTRE
255                                      DENIO DUARTE
256                               DENIS DERATANI MAUÁ
257                                     DENIS TAVEIRA
258                               DHARA AVELINO-ALVES
259                                     DIEGO BRANDÃO
260                                    DIEGO CARVALHO
261                               DIEGO DE SOUZA LIMA
262                                     DIEGO MARIANO
263                                     DIEGO MINATEL
264                                    DIEGO OLIVEIRA
265                                     DIEGO PEREIRA
266                             DIEINISON J. F. BRAGA
267                        DIMAS CASSIMIRO NASCIMENTO
268                              DIOGO V. DE S. SILVA
269                                 DOMINIQUE LAURENT
270                              DORGIVAL GUEDES NETO
271                                DOUGLAS E.V. PIRES
272                                    DUNCAN D. RUIZ
273                                       DÉBORA PINA
274                                    E. M. TEIXEIRA
275                                     E.R. HRUSCHKA
276                                     EDIMAR MANICA
277                             EDLENO SILVA DE MOURA
278                             EDMUNDO R. M. MADEIRA
279                                 EDNILZA E S NARDI
280                                      EDRÉ MOREIRA
281                                       EDSON ALVES
282                                 EDSON R. D. WEREN
283                                  EDUARDO A. RIBAS
284                               EDUARDO C. CARVALHO
285                             EDUARDO C. G. CAMARGO
286                          EDUARDO CUNHA DE ALMEIDA
287                              EDUARDO DIAS DEFREYN
288                    EDUARDO HENRIQUE MONTEIRO PENA
289                                   EDUARDO LUSTOSA
290                              EDUARDO NUNES BORGES
291                                 EDUARDO OGASAWARA
292                            EDUARDO R. DUARTE NETO
293                               EDUARDO R. HRUSCHKA
294                                     EDUARDO VALLE
295                                     EDWARD A. FOX
296                           EDWARD HERMANN HAEUSLER
297                                    EDWARD RIBEIRO
298                    ELAINE PARROS MACHADO DE SOUSA
299                                        ELI CORTEZ
300                                ELIANE G. KARASAWA
301                                    ELIANE MARTINS
302                                    ELIAS OLIVEIRA
303                                 ELISA S. MENENDEZ
304                         ELISANGELA ANDRADE ÂNGELO
305                                  ELISEU GUIMARÃES
306                                ELIVELTON F. BUENO
307                                       ELTON SERRA
308                               ELVERTON C. FAZZION
309                               EMANUEL F. COUTINHO
310                                     ENZO SERAPHIM
311                                   ERIK E. SANTISO
312                                         ERIK FALK
313                                      ERIKO WERBET
314                    ESTEVAM RAFAEL HRUSCHKA JUNIOR
315                               EVANDRINO G. BARROS
316                            EVANDRO L. T. P. CUNHA
317                             EVELINE R. SACRAMENTO
318                               EVERALDO COSTA NETO
319                                        F. QUÉCOLE
320                             FABIAN CORRÊA CARDOSO
321                                    FABIANA B. GIL
322                           FABIANA DA SILVA SOARES
323                                     FABIANO BALDO
324                                   FABIANO BOTELHO
325                               FABIANO MUNIZ BELÉM
326                               FABIO G. DE ANDRADE
327                                 FABIO J. COUTINHO
328                                 FABIO J. T. CHINO
329                                      FABIO MORAIS
330                                       FABIO PORTO
331                             FABIOLA S. F. PEREIRA
332                                 FABRÍCIO A. SILVA
333                               FABRÍCIO BENEVENUTO
334                                FABRÍCIO RODRIGUES
335                             FELIPE ALVES DA LOUZA
336                                  FELIPE BEVILAQUA
337                             FELIPE F. VASCONCELOS
338                            FELIPE FERREIRA BORGES
339                                FELIPE HOPPE LEVIN
340                             FELIPE L. S. FERREIRA
341                                  FELIPE MENEGUZZI
342                             FELIPE PINTO DA SILVA
343                        FELIPE VALENCIA DE ALMEIDA
344                             FELIPE X. B. DA SILVA
345                            FELIPPE PIRES FERREIRA
346                                    FERNANDA BAIÃO
347                      FERNANDA DE OLIVEIRA RAMALHO
348                           FERNANDA LÍGIA R. LOPES
349                            FERNANDA O. F. SCHMIDT
350                      FERNANDO DA FONSECA DE SOUZA
351                      FERNANDO L. BARROSO DA SILVA
352                                   FERNANDO MOURÃO
353                               FERNANDO T. PAULINO
354                                   FERNANDO TRINTA
355                              FILIPE DE L. ARCANJO
356                              FILIPE RIBEIRO NALON
357                                      FILIPE SILVA
358                                 FLAVIA BERNARDINI
359                                   FLAVIA DELICATO
360                     FLAVIO AUGUSTO VICENTE SEIXAS
361                              FLÁVIA MARIA SANTORO
362                                   FLÁVIO F. NOBRE
363                                FLÁVIO R. C. SOUSA
364                  FLÁVIO VINÍCIUS CRUZEIRO MARTINS
365                       FRANCISCO D. B. S. PRACIANO
366                                   FRANCISCO GOMES
367                           FRANKLIN SOUZA DA SILVA
368                                FREDERICO A. DURÃO

In [81]:

df_nomes_exportar = pd.DataFrame(nomes_pessoas_lista, columns=['nome_autor'])

df_nomes_exportar.to_csv('nomes_autores_distintos.csv', index=False, encoding='utf-8-sig')

print("Arquivo 'nomes_autores_distintos.csv' exportado com sucesso!")

Arquivo 'nomes_autores_distintos.csv' exportado com sucesso!

In [85]:
import pandas as pd

# Configuração de colunas conforme o seu ETL
cols_autores = [f'autor_{i}' for i in range(1, 9)]
cols_inst = [f'instituicao_{i}' for i in range(1, 9)]
cols_keywords = [f'keyword_{i}' for i in range(1, 6)]

# --- 1. UNIVERSIDADES (Ranking por presença em artigos) ---
# Conta em quantos artigos únicos cada universidade aparece
df_inst_long = df[['id'] + cols_inst].melt(id_vars='id', value_name='Instituicao').dropna()
ranking_inst = df_inst_long.groupby('Instituicao')['id'].nunique().reset_index(name='Total_Artigos')
ranking_inst = ranking_inst.sort_values('Total_Artigos', ascending=False)
ranking_inst.to_csv('ranking_universidades.csv', index=False, encoding='utf-8-sig')

# --- 2. AUTORES (Filtro: Colaboraram em mais de 1 artigo) ---
# Conta artigos por autor e filtra apenas os que possuem > 1
df_autores_long = df[['id'] + cols_autores].melt(id_vars='id', value_name='Autor').dropna()
ranking_autores = df_autores_long.groupby('Autor')['id'].nunique().reset_index(name='Qtd_Artigos')
ranking_autores = ranking_autores[ranking_autores['Qtd_Artigos'] > 1] # Filtro solicitado
ranking_autores = ranking_autores.sort_values('Qtd_Artigos', ascending=False)
ranking_autores.to_csv('ranking_autores_relevantes.csv', index=False, encoding='utf-8-sig')

# --- 3. UNIVERSIDADE X UNIVERSIDADE (Rede de Colaboração) ---
# Ordenado pelo peso (força da parceria entre as instituições)
rede_inst = df_inst_long.merge(df_inst_long, on='id')
rede_inst = rede_inst[rede_inst['Instituicao_x'] < rede_inst['Instituicao_y']]
colab_inst = rede_inst.groupby(['Instituicao_x', 'Instituicao_y']).size().reset_index(name='Peso_Colaboracao')
colab_inst = colab_inst.sort_values('Peso_Colaboracao', ascending=False)
colab_inst.to_csv('rede_instituicao_x_instituicao.csv', index=False, encoding='utf-8-sig')

# --- 4. AUTOR X AUTOR (Rede de Coautoria) ---
# Ordenado por quem mais trabalha junto
rede_autores = df_autores_long.merge(df_autores_long, on='id')
rede_autores = rede_autores[rede_autores['Autor_x'] < rede_autores['Autor_y']]
colab_autores = rede_autores.groupby(['Autor_x', 'Autor_y']).size().reset_index(name='Trabalhos_Juntos')
colab_autores = colab_autores.sort_values('Trabalhos_Juntos', ascending=False)
colab_autores.to_csv('rede_autor_x_autor.csv', index=False, encoding='utf-8-sig')

# --- 5. PALAVRAS-CHAVE / TEMAS (Ranking de Assuntos) ---
# Ordenado pelas palavras-chave mais frequentes
df_kw_long = df[['id'] + cols_keywords].melt(id_vars='id', value_name='Tema').dropna()
ranking_temas = df_kw_long.groupby('Tema').size().reset_index(name='Frequencia')
ranking_temas = ranking_temas.sort_values('Frequencia', ascending=False)
ranking_temas.to_csv('ranking_temas_artigos.csv', index=False, encoding='utf-8-sig')

print("✅ Todos os 5 CSVs foram gerados e ordenados com sucesso!")

✅ Todos os 5 CSVs foram gerados e ordenados com sucesso!